// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dydxprotocol/agentwallet/agentwallet.proto

package chainmsgs

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Limits is what a root delegation grants.
//
// These are the ceiling. An SVP-DT credential chain carries its own caveats and
// may only narrow them further, so the effective grant for any execution is the
// intersection of this record with every token in the chain — a credential can
// never widen what the user signed here.
type Limits struct {
	// Lifetime cap on directly spendable value.
	SpendLimitTotal []types.Coin `protobuf:"bytes,1,rep,name=spend_limit_total,json=spendLimitTotal,proto3" json:"spend_limit_total"`
	// Per-day cap on directly spendable value, reset by a day-bucketed key
	// rather than by a scheduled job.
	SpendLimitDaily []types.Coin `protobuf:"bytes,2,rep,name=spend_limit_daily,json=spendLimitDaily,proto3" json:"spend_limit_daily"`
	// Lifetime cap on buying downstream agent services.
	//
	// Separate from spend_limit because they fund different things: without it, a
	// user who authorised "trade up to 1000 USDC" would find that allowance burnt
	// on paid API calls to other agents.
	SvcSpendLimitTotal []types.Coin `protobuf:"bytes,3,rep,name=svc_spend_limit_total,json=svcSpendLimitTotal,proto3" json:"svc_spend_limit_total"`
	// Per-day cap on buying downstream agent services.
	SvcSpendLimitDaily []types.Coin `protobuf:"bytes,4,rep,name=svc_spend_limit_daily,json=svcSpendLimitDaily,proto3" json:"svc_spend_limit_daily"`
	// Denominations the agent may move. Empty grants none.
	Denoms []string `protobuf:"bytes,5,rep,name=denoms,proto3" json:"denoms,omitempty"`
	// Action identifiers the agent may perform, sharing a namespace with the
	// policy layer, e.g. "clob.place_order". Empty grants none.
	Actions []string `protobuf:"bytes,6,rep,name=actions,proto3" json:"actions,omitempty"`
	// A2A skills the agent may be asked for. Empty grants none.
	Skills []string `protobuf:"bytes,7,rep,name=skills,proto3" json:"skills,omitempty"`
	// EVM contracts the agent may call. Empty grants none.
	Contracts []string `protobuf:"bytes,8,rep,name=contracts,proto3" json:"contracts,omitempty"`
	// Subaccount numbers the agent may operate on — the blast radius.
	//
	// This is what confines a delegated agent to the collateral the user set
	// aside for it: an agent authorised for subaccount 7 cannot reach the
	// holdings in subaccount 0. Empty grants none.
	Subaccounts []uint32 `protobuf:"varint,9,rep,packed,name=subaccounts,proto3" json:"subaccounts,omitempty"`
	// Longest credential chain permitted beneath this delegation.
	MaxDepth uint32 `protobuf:"varint,10,opt,name=max_depth,json=maxDepth,proto3" json:"max_depth,omitempty"`
	// Longest validity window any single credential under this delegation may
	// carry. Short windows are what bound how long a revocation takes to become
	// visible to off-chain holders.
	MaxTokenTtlSeconds uint32 `protobuf:"varint,11,opt,name=max_token_ttl_seconds,json=maxTokenTtlSeconds,proto3" json:"max_token_ttl_seconds,omitempty"`
}

func (m *Limits) Reset()         { *m = Limits{} }
func (m *Limits) String() string { return proto.CompactTextString(m) }
func (*Limits) ProtoMessage()    {}
func (*Limits) Descriptor() ([]byte, []int) {
	return fileDescriptor_bca28d4487709b90, []int{0}
}
func (m *Limits) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Limits) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Limits.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Limits) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Limits.Merge(m, src)
}
func (m *Limits) XXX_Size() int {
	return m.Size()
}
func (m *Limits) XXX_DiscardUnknown() {
	xxx_messageInfo_Limits.DiscardUnknown(m)
}

var xxx_messageInfo_Limits proto.InternalMessageInfo

func (m *Limits) GetSpendLimitTotal() []types.Coin {
	if m != nil {
		return m.SpendLimitTotal
	}
	return nil
}

func (m *Limits) GetSpendLimitDaily() []types.Coin {
	if m != nil {
		return m.SpendLimitDaily
	}
	return nil
}

func (m *Limits) GetSvcSpendLimitTotal() []types.Coin {
	if m != nil {
		return m.SvcSpendLimitTotal
	}
	return nil
}

func (m *Limits) GetSvcSpendLimitDaily() []types.Coin {
	if m != nil {
		return m.SvcSpendLimitDaily
	}
	return nil
}

func (m *Limits) GetDenoms() []string {
	if m != nil {
		return m.Denoms
	}
	return nil
}

func (m *Limits) GetActions() []string {
	if m != nil {
		return m.Actions
	}
	return nil
}

func (m *Limits) GetSkills() []string {
	if m != nil {
		return m.Skills
	}
	return nil
}

func (m *Limits) GetContracts() []string {
	if m != nil {
		return m.Contracts
	}
	return nil
}

func (m *Limits) GetSubaccounts() []uint32 {
	if m != nil {
		return m.Subaccounts
	}
	return nil
}

func (m *Limits) GetMaxDepth() uint32 {
	if m != nil {
		return m.MaxDepth
	}
	return 0
}

func (m *Limits) GetMaxTokenTtlSeconds() uint32 {
	if m != nil {
		return m.MaxTokenTtlSeconds
	}
	return 0
}

// Delegation is a user's on-chain grant to a platform agent, and the root every
// SVP-DT credential chain descends from.
//
// Credentials themselves are issued off chain and never touch state; this
// record is what they are anchored to, and the only thing that can revoke them.
type Delegation struct {
	// Deterministic 32-byte id, derived from the delegator, the agent and a
	// per-delegator sequence. Derived rather than random because state
	// transitions must be reproducible across validators.
	RootId []byte `protobuf:"bytes,1,opt,name=root_id,json=rootId,proto3" json:"root_id,omitempty"`
	// The user. Every action taken under this delegation must operate on this
	// account — the assertion that keeps positions, margin and risk with the
	// user rather than the agent executing for them.
	Delegator string `protobuf:"bytes,2,opt,name=delegator,proto3" json:"delegator,omitempty"`
	// DID of the agent this delegation was granted to, which is the only party
	// that may issue depth-1 credentials beneath it.
	AgentId string `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// The ceiling on what may be done under this delegation.
	Limits Limits `protobuf:"bytes,4,opt,name=limits,proto3" json:"limits"`
	// Revocation heartbeat, incremented on every change to this record.
	//
	// Credentials embed the epoch they were issued against, so a single
	// increment invalidates every credential already issued beneath this
	// delegation at once — however many have been handed out, and wherever they
	// have travelled. This is what makes a user's emergency stop immediate
	// without having to find and revoke each credential individually.
	Epoch uint64 `protobuf:"varint,5,opt,name=epoch,proto3" json:"epoch,omitempty"`
	// True while the delegation is suspended. Distinct from revocation: a pause
	// is reversible, and the record and its ledgers survive it.
	Paused bool `protobuf:"varint,6,opt,name=paused,proto3" json:"paused,omitempty"`
	// Unix seconds after which no credential under this delegation verifies.
	ExpiresAt int64 `protobuf:"varint,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// Height at which the delegation was created.
	CreatedAtHeight uint64 `protobuf:"varint,8,opt,name=created_at_height,json=createdAtHeight,proto3" json:"created_at_height,omitempty"`
}

func (m *Delegation) Reset()         { *m = Delegation{} }
func (m *Delegation) String() string { return proto.CompactTextString(m) }
func (*Delegation) ProtoMessage()    {}
func (*Delegation) Descriptor() ([]byte, []int) {
	return fileDescriptor_bca28d4487709b90, []int{1}
}
func (m *Delegation) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Delegation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Delegation.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Delegation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Delegation.Merge(m, src)
}
func (m *Delegation) XXX_Size() int {
	return m.Size()
}
func (m *Delegation) XXX_DiscardUnknown() {
	xxx_messageInfo_Delegation.DiscardUnknown(m)
}

var xxx_messageInfo_Delegation proto.InternalMessageInfo

func (m *Delegation) GetRootId() []byte {
	if m != nil {
		return m.RootId
	}
	return nil
}

func (m *Delegation) GetDelegator() string {
	if m != nil {
		return m.Delegator
	}
	return ""
}

func (m *Delegation) GetAgentId() string {
	if m != nil {
		return m.AgentId
	}
	return ""
}

func (m *Delegation) GetLimits() Limits {
	if m != nil {
		return m.Limits
	}
	return Limits{}
}

func (m *Delegation) GetEpoch() uint64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *Delegation) GetPaused() bool {
	if m != nil {
		return m.Paused
	}
	return false
}

func (m *Delegation) GetExpiresAt() int64 {
	if m != nil {
		return m.ExpiresAt
	}
	return 0
}

func (m *Delegation) GetCreatedAtHeight() uint64 {
	if m != nil {
		return m.CreatedAtHeight
	}
	return 0
}

// Spend is a running total against a delegation's limits.
//
// Held separately from Delegation so that recording an expenditure does not
// rewrite the grant itself, and so lifetime and per-day totals can share one
// value type under different keys.
type Spend struct {
	// Value spent directly.
	Spent []types.Coin `protobuf:"bytes,1,rep,name=spent,proto3" json:"spent"`
	// Value spent buying downstream agent services.
	SvcSpent []types.Coin `protobuf:"bytes,2,rep,name=svc_spent,json=svcSpent,proto3" json:"svc_spent"`
}

func (m *Spend) Reset()         { *m = Spend{} }
func (m *Spend) String() string { return proto.CompactTextString(m) }
func (*Spend) ProtoMessage()    {}
func (*Spend) Descriptor() ([]byte, []int) {
	return fileDescriptor_bca28d4487709b90, []int{2}
}
func (m *Spend) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Spend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Spend.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Spend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Spend.Merge(m, src)
}
func (m *Spend) XXX_Size() int {
	return m.Size()
}
func (m *Spend) XXX_DiscardUnknown() {
	xxx_messageInfo_Spend.DiscardUnknown(m)
}

var xxx_messageInfo_Spend proto.InternalMessageInfo

func (m *Spend) GetSpent() []types.Coin {
	if m != nil {
		return m.Spent
	}
	return nil
}

func (m *Spend) GetSvcSpent() []types.Coin {
	if m != nil {
		return m.SvcSpent
	}
	return nil
}

// DelegationProof is the credential chain accompanying a delegated execution.
type DelegationProof struct {
	// The chain from depth 1 to the leaf, each a canonical CBOR encoded SVP-DT
	// token. Verified as a whole: signatures, parent linkage, and that capability
	// only ever narrows.
	Tokens [][]byte `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"`
	// Optional handle for a chain already anchored on chain, letting a repeated
	// caller skip re-verifying signatures. Reserved; unused until anchoring
	// exists, and must be empty until then.
	DelegRef []byte `protobuf:"bytes,2,opt,name=deleg_ref,json=delegRef,proto3" json:"deleg_ref,omitempty"`
}

func (m *DelegationProof) Reset()         { *m = DelegationProof{} }
func (m *DelegationProof) String() string { return proto.CompactTextString(m) }
func (*DelegationProof) ProtoMessage()    {}
func (*DelegationProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_bca28d4487709b90, []int{3}
}
func (m *DelegationProof) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DelegationProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DelegationProof.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DelegationProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelegationProof.Merge(m, src)
}
func (m *DelegationProof) XXX_Size() int {
	return m.Size()
}
func (m *DelegationProof) XXX_DiscardUnknown() {
	xxx_messageInfo_DelegationProof.DiscardUnknown(m)
}

var xxx_messageInfo_DelegationProof proto.InternalMessageInfo

func (m *DelegationProof) GetTokens() [][]byte {
	if m != nil {
		return m.Tokens
	}
	return nil
}

func (m *DelegationProof) GetDelegRef() []byte {
	if m != nil {
		return m.DelegRef
	}
	return nil
}

// DelegatedOrderRef ties an order back to the delegation it was placed under.
//
// Written when a delegated order is placed and read when it fills, because
// those happen in different blocks: without it, a fill carries no way to
// attribute itself or to charge the right delegation's budget.
type DelegatedOrderRef struct {
	// Root delegation the order was placed under.
	RootId []byte `protobuf:"bytes,1,opt,name=root_id,json=rootId,proto3" json:"root_id,omitempty"`
	// Digest of the credential chain that authorised it, for audit.
	TokenChainHash []byte `protobuf:"bytes,2,opt,name=token_chain_hash,json=tokenChainHash,proto3" json:"token_chain_hash,omitempty"`
	// DID of the agent that placed it. Attribution only — the position belongs
	// to the delegator throughout.
	ExecutorAgentId string `protobuf:"bytes,3,opt,name=executor_agent_id,json=executorAgentId,proto3" json:"executor_agent_id,omitempty"`
}

func (m *DelegatedOrderRef) Reset()         { *m = DelegatedOrderRef{} }
func (m *DelegatedOrderRef) String() string { return proto.CompactTextString(m) }
func (*DelegatedOrderRef) ProtoMessage()    {}
func (*DelegatedOrderRef) Descriptor() ([]byte, []int) {
	return fileDescriptor_bca28d4487709b90, []int{4}
}
func (m *DelegatedOrderRef) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DelegatedOrderRef) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DelegatedOrderRef.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DelegatedOrderRef) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelegatedOrderRef.Merge(m, src)
}
func (m *DelegatedOrderRef) XXX_Size() int {
	return m.Size()
}
func (m *DelegatedOrderRef) XXX_DiscardUnknown() {
	xxx_messageInfo_DelegatedOrderRef.DiscardUnknown(m)
}

var xxx_messageInfo_DelegatedOrderRef proto.InternalMessageInfo

func (m *DelegatedOrderRef) GetRootId() []byte {
	if m != nil {
		return m.RootId
	}
	return nil
}

func (m *DelegatedOrderRef) GetTokenChainHash() []byte {
	if m != nil {
		return m.TokenChainHash
	}
	return nil
}

func (m *DelegatedOrderRef) GetExecutorAgentId() string {
	if m != nil {
		return m.ExecutorAgentId
	}
	return ""
}

func init() {
	proto.RegisterType((*Limits)(nil), "dydxprotocol.agentwallet.Limits")
	proto.RegisterType((*Delegation)(nil), "dydxprotocol.agentwallet.Delegation")
	proto.RegisterType((*Spend)(nil), "dydxprotocol.agentwallet.Spend")
	proto.RegisterType((*DelegationProof)(nil), "dydxprotocol.agentwallet.DelegationProof")
	proto.RegisterType((*DelegatedOrderRef)(nil), "dydxprotocol.agentwallet.DelegatedOrderRef")
}

func init() {
	proto.RegisterFile("dydxprotocol/agentwallet/agentwallet.proto", fileDescriptor_bca28d4487709b90)
}

var fileDescriptor_bca28d4487709b90 = []byte{
	// 727 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xdd, 0x4e, 0x1b, 0x39,
	0x14, 0xce, 0x90, 0xdf, 0x71, 0x60, 0xb3, 0x58, 0xb0, 0x6b, 0xd8, 0xdd, 0xec, 0x28, 0x57, 0x23,
	0x24, 0x26, 0x82, 0xdd, 0xf6, 0xaa, 0xad, 0x14, 0x40, 0x15, 0xa8, 0x95, 0x5a, 0x0d, 0x48, 0x95,
	0x7a, 0x33, 0x72, 0x6c, 0x27, 0x33, 0x62, 0x32, 0x8e, 0xc6, 0x27, 0x69, 0x90, 0x7a, 0xd5, 0x27,
	0xe8, 0x43, 0xf4, 0x05, 0x2a, 0xf5, 0x21, 0xb8, 0x44, 0xbd, 0xea, 0x55, 0x55, 0xc1, 0x8b, 0x54,
	0xb6, 0x87, 0x12, 0x68, 0x91, 0x68, 0xef, 0xe6, 0xfb, 0xbe, 0x73, 0xbe, 0x9c, 0xf8, 0x7c, 0x36,
	0xda, 0xe0, 0x27, 0x7c, 0x36, 0xce, 0x25, 0x48, 0x26, 0xd3, 0x2e, 0x1d, 0x8a, 0x0c, 0x5e, 0xd1,
	0x34, 0x15, 0x30, 0xff, 0x1d, 0x98, 0x02, 0x4c, 0xe6, 0x6b, 0x83, 0x39, 0x7d, 0x7d, 0x8d, 0x49,
	0x35, 0x92, 0x2a, 0x32, 0x62, 0xd7, 0x02, 0xdb, 0xb4, 0xbe, 0x32, 0x94, 0x43, 0x69, 0x79, 0xfd,
	0x55, 0xb0, 0x6d, 0x5b, 0xd3, 0xed, 0x53, 0x25, 0xba, 0xd3, 0xad, 0xbe, 0x00, 0xba, 0xd5, 0x65,
	0x32, 0xc9, 0xac, 0xde, 0x79, 0x57, 0x41, 0xb5, 0xa7, 0xc9, 0x28, 0x01, 0x85, 0x9f, 0xa0, 0x65,
	0x35, 0x16, 0x19, 0x8f, 0x52, 0x8d, 0x23, 0x90, 0x40, 0x53, 0xe2, 0x78, 0x65, 0xbf, 0xb9, 0xbd,
	0x16, 0x14, 0x3f, 0xa5, 0x6d, 0x82, 0xc2, 0x26, 0xd8, 0x95, 0x49, 0xb6, 0x53, 0x39, 0xfd, 0xfc,
	0x6f, 0x29, 0x6c, 0x99, 0x4e, 0x63, 0x74, 0xa4, 0xfb, 0x6e, 0x9a, 0x71, 0x9a, 0xa4, 0x27, 0x64,
	0xe1, 0xa7, 0xcd, 0xf6, 0x74, 0x1f, 0x0e, 0xd1, 0xaa, 0x9a, 0xb2, 0xe8, 0xfb, 0xe9, 0xca, 0x77,
	0x33, 0xc4, 0x6a, 0xca, 0x0e, 0x6f, 0x0c, 0xf8, 0x03, 0x4f, 0x3b, 0x64, 0xe5, 0x57, 0x3c, 0xed,
	0x9c, 0x7f, 0xa0, 0x1a, 0x17, 0x99, 0x1c, 0x29, 0x52, 0xf5, 0xca, 0xbe, 0x1b, 0x16, 0x08, 0x13,
	0x54, 0xa7, 0x0c, 0x12, 0x99, 0x29, 0x52, 0x33, 0xc2, 0x25, 0xd4, 0x1d, 0xea, 0x38, 0x49, 0x53,
	0x45, 0xea, 0xb6, 0xc3, 0x22, 0xfc, 0x37, 0x72, 0x99, 0xcc, 0x20, 0xa7, 0x0c, 0x14, 0x69, 0x18,
	0xe9, 0x8a, 0xc0, 0x1e, 0x6a, 0xaa, 0x49, 0x9f, 0x32, 0x26, 0x27, 0x19, 0x28, 0xe2, 0x7a, 0x65,
	0x7f, 0x29, 0x9c, 0xa7, 0xf0, 0x5f, 0xc8, 0x1d, 0xd1, 0x59, 0xc4, 0xc5, 0x18, 0x62, 0x82, 0x3c,
	0xc7, 0x5f, 0x0a, 0x1b, 0x23, 0x3a, 0xdb, 0xd3, 0x18, 0x6f, 0xa1, 0x55, 0x2d, 0x82, 0x3c, 0x16,
	0x59, 0x04, 0x90, 0x46, 0x4a, 0x30, 0x99, 0x71, 0x45, 0x9a, 0xa6, 0x10, 0x8f, 0xe8, 0xec, 0x48,
	0x6b, 0x47, 0x90, 0x1e, 0x5a, 0xa5, 0xf3, 0x7e, 0x01, 0xa1, 0x3d, 0x91, 0x8a, 0x21, 0xd5, 0x73,
	0xe3, 0x3f, 0x51, 0x3d, 0x97, 0x12, 0xa2, 0x84, 0x13, 0xc7, 0x73, 0xfc, 0xc5, 0xb0, 0xa6, 0xe1,
	0x01, 0xc7, 0xf7, 0x91, 0xcb, 0x6d, 0x99, 0xcc, 0xc9, 0x82, 0xe7, 0xf8, 0xee, 0x0e, 0xf9, 0xf8,
	0x61, 0x73, 0xa5, 0x38, 0xcc, 0x1e, 0xe7, 0xb9, 0x50, 0xea, 0x10, 0xf2, 0x24, 0x1b, 0x86, 0x57,
	0xa5, 0x78, 0x0d, 0x35, 0x4c, 0xcc, 0xb5, 0x63, 0x59, 0xb7, 0x85, 0x75, 0x83, 0x0f, 0x38, 0x7e,
	0x84, 0x6a, 0x66, 0x3d, 0x8a, 0x54, 0x3c, 0xc7, 0x6f, 0x6e, 0x7b, 0xc1, 0x6d, 0xb7, 0x23, 0xb0,
	0x41, 0x2e, 0x16, 0x54, 0x74, 0xe1, 0x15, 0x54, 0x15, 0x63, 0xc9, 0x62, 0x52, 0xf5, 0x1c, 0xbf,
	0x12, 0x5a, 0xa0, 0x0f, 0x7e, 0x4c, 0x27, 0x4a, 0x70, 0x52, 0xf3, 0x1c, 0xbf, 0x11, 0x16, 0x08,
	0xff, 0x83, 0x90, 0x98, 0x8d, 0x93, 0x5c, 0xa8, 0x88, 0x02, 0xa9, 0x7b, 0x8e, 0x5f, 0x0e, 0xdd,
	0x82, 0xe9, 0x01, 0xde, 0x40, 0xcb, 0x2c, 0x17, 0x14, 0x04, 0x8f, 0x28, 0x44, 0xb1, 0x48, 0x86,
	0x31, 0x90, 0x86, 0x31, 0x6e, 0x15, 0x42, 0x0f, 0xf6, 0x0d, 0xdd, 0x79, 0x8d, 0xaa, 0x26, 0x20,
	0xf8, 0x1e, 0xaa, 0xea, 0x98, 0xc1, 0x5d, 0x2f, 0x93, 0xad, 0xc6, 0x0f, 0x90, 0x7b, 0x99, 0x50,
	0xb8, 0xeb, 0xd5, 0x69, 0x14, 0xa9, 0x84, 0xce, 0x63, 0xd4, 0xba, 0x5a, 0xd8, 0xf3, 0x5c, 0xca,
	0x81, 0xfe, 0xcf, 0x66, 0xe7, 0xca, 0x0c, 0xb2, 0x18, 0x16, 0x48, 0x87, 0xc5, 0x6c, 0x22, 0xca,
	0xc5, 0xc0, 0x2c, 0x6d, 0x31, 0x6c, 0x18, 0x22, 0x14, 0x83, 0xce, 0x1b, 0x07, 0x2d, 0x17, 0x46,
	0x82, 0x3f, 0xcb, 0xb9, 0xc8, 0x43, 0x31, 0xb8, 0x3d, 0x00, 0x3e, 0xfa, 0xdd, 0xe6, 0x8a, 0xc5,
	0x34, 0xc9, 0xa2, 0x98, 0xaa, 0xb8, 0xb0, 0xfc, 0xcd, 0xf0, 0xbb, 0x9a, 0xde, 0xa7, 0x2a, 0xd6,
	0x47, 0x29, 0x66, 0x82, 0x4d, 0x40, 0xe6, 0xd1, 0x8d, 0xdd, 0xb7, 0x2e, 0x85, 0x9e, 0xcd, 0xc0,
	0xce, 0x8b, 0xd3, 0xf3, 0xb6, 0x73, 0x76, 0xde, 0x76, 0xbe, 0x9c, 0xb7, 0x9d, 0xb7, 0x17, 0xed,
	0xd2, 0xd9, 0x45, 0xbb, 0xf4, 0xe9, 0xa2, 0x5d, 0x7a, 0xf9, 0x70, 0x98, 0x40, 0x3c, 0xe9, 0x07,
	0x4c, 0x8e, 0xba, 0xd7, 0x5e, 0xd8, 0xe9, 0xff, 0x9b, 0x66, 0x84, 0xee, 0x37, 0x66, 0x76, 0xed,
	0xd5, 0x85, 0x93, 0xb1, 0x50, 0xfd, 0x9a, 0x51, 0xff, 0xfb, 0x1a, 0x00, 0x00, 0xff, 0xff, 0x78,
	0x38, 0xbf, 0xd2, 0x9e, 0x05, 0x00, 0x00,
}

func (m *Limits) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Limits) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Limits) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MaxTokenTtlSeconds != 0 {
		i = encodeVarintAgentwallet(dAtA, i, uint64(m.MaxTokenTtlSeconds))
		i--
		dAtA[i] = 0x58
	}
	if m.MaxDepth != 0 {
		i = encodeVarintAgentwallet(dAtA, i, uint64(m.MaxDepth))
		i--
		dAtA[i] = 0x50
	}
	if len(m.Subaccounts) > 0 {
		dAtA2 := make([]byte, len(m.Subaccounts)*10)
		var j1 int
		for _, num := range m.Subaccounts {
			for num >= 1<<7 {
				dAtA2[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA2[j1] = uint8(num)
			j1++
		}
		i -= j1
		copy(dAtA[i:], dAtA2[:j1])
		i = encodeVarintAgentwallet(dAtA, i, uint64(j1))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.Contracts) > 0 {
		for iNdEx := len(m.Contracts) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Contracts[iNdEx])
			copy(dAtA[i:], m.Contracts[iNdEx])
			i = encodeVarintAgentwallet(dAtA, i, uint64(len(m.Contracts[iNdEx])))
			i--
			dAtA[i] = 0x42
		}
	}
	if len(m.Skills) > 0 {
		for iNdEx := len(m.Skills) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Skills[iNdEx])
			copy(dAtA[i:], m.Skills[iNdEx])
			i = encodeVarintAgentwallet(dAtA, i, uint64(len(m.Skills[iNdEx])))
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.Actions) > 0 {
		for iNdEx := len(m.Actions) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Actions[iNdEx])
			copy(dAtA[i:], m.Actions[iNdEx])
			i = encodeVarintAgentwallet(dAtA, i, uint64(len(m.Actions[iNdEx])))
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.Denoms) > 0 {
		for iNdEx := len(m.Denoms) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Denoms[iNdEx])
			copy(dAtA[i:], m.Denoms[iNdEx])
			i = encodeVarintAgentwallet(dAtA, i, uint64(len(m.Denoms[iNdEx])))
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.SvcSpendLimitDaily) > 0 {
		for iNdEx := len(m.SvcSpendLimitDaily) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SvcSpendLimitDaily[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintAgentwallet(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.SvcSpendLimitTotal) > 0 {
		for iNdEx := len(m.SvcSpendLimitTotal) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SvcSpendLimitTotal[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintAgentwallet(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.SpendLimitDaily) > 0 {
		for iNdEx := len(m.SpendLimitDaily) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SpendLimitDaily[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintAgentwallet(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.SpendLimitTotal) > 0 {
		for iNdEx := len(m.SpendLimitTotal) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SpendLimitTotal[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintAgentwallet(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *Delegation) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Delegation) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Delegation) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CreatedAtHeight != 0 {
		i = encodeVarintAgentwallet(dAtA, i, uint64(m.CreatedAtHeight))
		i--
		dAtA[i] = 0x40
	}
	if m.ExpiresAt != 0 {
		i = encodeVarintAgentwallet(dAtA, i, uint64(m.ExpiresAt))
		i--
		dAtA[i] = 0x38
	}
	if m.Paused {
		i--
		if m.Paused {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	if m.Epoch != 0 {
		i = encodeVarintAgentwallet(dAtA, i, uint64(m.Epoch))
		i--
		dAtA[i] = 0x28
	}
	{
		size, err := m.Limits.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintAgentwallet(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.AgentId) > 0 {
		i -= len(m.AgentId)
		copy(dAtA[i:], m.AgentId)
		i = encodeVarintAgentwallet(dAtA, i, uint64(len(m.AgentId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Delegator) > 0 {
		i -= len(m.Delegator)
		copy(dAtA[i:], m.Delegator)
		i = encodeVarintAgentwallet(dAtA, i, uint64(len(m.Delegator)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.RootId) > 0 {
		i -= len(m.RootId)
		copy(dAtA[i:], m.RootId)
		i = encodeVarintAgentwallet(dAtA, i, uint64(len(m.RootId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Spend) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Spend) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Spend) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SvcSpent) > 0 {
		for iNdEx := len(m.SvcSpent) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SvcSpent[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintAgentwallet(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Spent) > 0 {
		for iNdEx := len(m.Spent) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Spent[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintAgentwallet(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *DelegationProof) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DelegationProof) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DelegationProof) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DelegRef) > 0 {
		i -= len(m.DelegRef)
		copy(dAtA[i:], m.DelegRef)
		i = encodeVarintAgentwallet(dAtA, i, uint64(len(m.DelegRef)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Tokens) > 0 {
		for iNdEx := len(m.Tokens) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Tokens[iNdEx])
			copy(dAtA[i:], m.Tokens[iNdEx])
			i = encodeVarintAgentwallet(dAtA, i, uint64(len(m.Tokens[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *DelegatedOrderRef) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DelegatedOrderRef) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DelegatedOrderRef) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ExecutorAgentId) > 0 {
		i -= len(m.ExecutorAgentId)
		copy(dAtA[i:], m.ExecutorAgentId)
		i = encodeVarintAgentwallet(dAtA, i, uint64(len(m.ExecutorAgentId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.TokenChainHash) > 0 {
		i -= len(m.TokenChainHash)
		copy(dAtA[i:], m.TokenChainHash)
		i = encodeVarintAgentwallet(dAtA, i, uint64(len(m.TokenChainHash)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.RootId) > 0 {
		i -= len(m.RootId)
		copy(dAtA[i:], m.RootId)
		i = encodeVarintAgentwallet(dAtA, i, uint64(len(m.RootId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintAgentwallet(dAtA []byte, offset int, v uint64) int {
	offset -= sovAgentwallet(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Limits) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.SpendLimitTotal) > 0 {
		for _, e := range m.SpendLimitTotal {
			l = e.Size()
			n += 1 + l + sovAgentwallet(uint64(l))
		}
	}
	if len(m.SpendLimitDaily) > 0 {
		for _, e := range m.SpendLimitDaily {
			l = e.Size()
			n += 1 + l + sovAgentwallet(uint64(l))
		}
	}
	if len(m.SvcSpendLimitTotal) > 0 {
		for _, e := range m.SvcSpendLimitTotal {
			l = e.Size()
			n += 1 + l + sovAgentwallet(uint64(l))
		}
	}
	if len(m.SvcSpendLimitDaily) > 0 {
		for _, e := range m.SvcSpendLimitDaily {
			l = e.Size()
			n += 1 + l + sovAgentwallet(uint64(l))
		}
	}
	if len(m.Denoms) > 0 {
		for _, s := range m.Denoms {
			l = len(s)
			n += 1 + l + sovAgentwallet(uint64(l))
		}
	}
	if len(m.Actions) > 0 {
		for _, s := range m.Actions {
			l = len(s)
			n += 1 + l + sovAgentwallet(uint64(l))
		}
	}
	if len(m.Skills) > 0 {
		for _, s := range m.Skills {
			l = len(s)
			n += 1 + l + sovAgentwallet(uint64(l))
		}
	}
	if len(m.Contracts) > 0 {
		for _, s := range m.Contracts {
			l = len(s)
			n += 1 + l + sovAgentwallet(uint64(l))
		}
	}
	if len(m.Subaccounts) > 0 {
		l = 0
		for _, e := range m.Subaccounts {
			l += sovAgentwallet(uint64(e))
		}
		n += 1 + sovAgentwallet(uint64(l)) + l
	}
	if m.MaxDepth != 0 {
		n += 1 + sovAgentwallet(uint64(m.MaxDepth))
	}
	if m.MaxTokenTtlSeconds != 0 {
		n += 1 + sovAgentwallet(uint64(m.MaxTokenTtlSeconds))
	}
	return n
}

func (m *Delegation) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.RootId)
	if l > 0 {
		n += 1 + l + sovAgentwallet(uint64(l))
	}
	l = len(m.Delegator)
	if l > 0 {
		n += 1 + l + sovAgentwallet(uint64(l))
	}
	l = len(m.AgentId)
	if l > 0 {
		n += 1 + l + sovAgentwallet(uint64(l))
	}
	l = m.Limits.Size()
	n += 1 + l + sovAgentwallet(uint64(l))
	if m.Epoch != 0 {
		n += 1 + sovAgentwallet(uint64(m.Epoch))
	}
	if m.Paused {
		n += 2
	}
	if m.ExpiresAt != 0 {
		n += 1 + sovAgentwallet(uint64(m.ExpiresAt))
	}
	if m.CreatedAtHeight != 0 {
		n += 1 + sovAgentwallet(uint64(m.CreatedAtHeight))
	}
	return n
}

func (m *Spend) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Spent) > 0 {
		for _, e := range m.Spent {
			l = e.Size()
			n += 1 + l + sovAgentwallet(uint64(l))
		}
	}
	if len(m.SvcSpent) > 0 {
		for _, e := range m.SvcSpent {
			l = e.Size()
			n += 1 + l + sovAgentwallet(uint64(l))
		}
	}
	return n
}

func (m *DelegationProof) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Tokens) > 0 {
		for _, b := range m.Tokens {
			l = len(b)
			n += 1 + l + sovAgentwallet(uint64(l))
		}
	}
	l = len(m.DelegRef)
	if l > 0 {
		n += 1 + l + sovAgentwallet(uint64(l))
	}
	return n
}

func (m *DelegatedOrderRef) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.RootId)
	if l > 0 {
		n += 1 + l + sovAgentwallet(uint64(l))
	}
	l = len(m.TokenChainHash)
	if l > 0 {
		n += 1 + l + sovAgentwallet(uint64(l))
	}
	l = len(m.ExecutorAgentId)
	if l > 0 {
		n += 1 + l + sovAgentwallet(uint64(l))
	}
	return n
}

func sovAgentwallet(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozAgentwallet(x uint64) (n int) {
	return sovAgentwallet(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Limits) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAgentwallet
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Limits: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Limits: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SpendLimitTotal", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAgentwallet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAgentwallet
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAgentwallet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SpendLimitTotal = append(m.SpendLimitTotal, types.Coin{})
			if err := m.SpendLimitTotal[len(m.SpendLimitTotal)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SpendLimitDaily", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAgentwallet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAgentwallet
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAgentwallet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SpendLimitDaily = append(m.SpendLimitDaily, types.Coin{})
			if err := m.SpendLimitDaily[len(m.SpendLimitDaily)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SvcSpendLimitTotal", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAgentwallet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAgentwallet
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAgentwallet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SvcSpendLimitTotal = append(m.SvcSpendLimitTotal, types.Coin{})
			if err := m.SvcSpendLimitTotal[len(m.SvcSpendLimitTotal)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SvcSpendLimitDaily", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAgentwallet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAgentwallet
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAgentwallet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SvcSpendLimitDaily = append(m.SvcSpendLimitDaily, types.Coin{})
			if err := m.SvcSpendLimitDaily[len(m.SvcSpendLimitDaily)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denoms", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAgentwallet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAgentwallet
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAgentwallet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denoms = append(m.Denoms, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Actions", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAgentwallet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAgentwallet
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAgentwallet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Actions = append(m.Actions, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Skills", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAgentwallet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAgentwallet
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAgentwallet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Skills = append(m.Skills, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Contracts", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAgentwallet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAgentwallet
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAgentwallet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Contracts = append(m.Contracts, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 9:
			if wireType == 0 {
				var v uint32
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowAgentwallet
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint32(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Subaccounts = append(m.Subaccounts, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowAgentwallet
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthAgentwallet
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthAgentwallet
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.Subaccounts) == 0 {
					m.Subaccounts = make([]uint32, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint32
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowAgentwallet
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint32(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Subaccounts = append(m.Subaccounts, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Subaccounts", wireType)
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxDepth", wireType)
			}
			m.MaxDepth = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAgentwallet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxDepth |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxTokenTtlSeconds", wireType)
			}
			m.MaxTokenTtlSeconds = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAgentwallet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxTokenTtlSeconds |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipAgentwallet(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAgentwallet
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Delegation) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAgentwallet
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Delegation: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Delegation: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RootId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAgentwallet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthAgentwallet
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthAgentwallet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RootId = append(m.RootId[:0], dAtA[iNdEx:postIndex]...)
			if m.RootId == nil {
				m.RootId = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Delegator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAgentwallet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAgentwallet
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAgentwallet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Delegator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AgentId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAgentwallet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAgentwallet
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAgentwallet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AgentId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Limits", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAgentwallet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAgentwallet
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAgentwallet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Limits.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Epoch", wireType)
			}
			m.Epoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAgentwallet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Epoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Paused", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAgentwallet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Paused = bool(v != 0)
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpiresAt", wireType)
			}
			m.ExpiresAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAgentwallet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExpiresAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAtHeight", wireType)
			}
			m.CreatedAtHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAgentwallet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAtHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipAgentwallet(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAgentwallet
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Spend) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAgentwallet
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Spend: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Spend: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Spent", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAgentwallet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAgentwallet
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAgentwallet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Spent = append(m.Spent, types.Coin{})
			if err := m.Spent[len(m.Spent)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SvcSpent", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAgentwallet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAgentwallet
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAgentwallet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SvcSpent = append(m.SvcSpent, types.Coin{})
			if err := m.SvcSpent[len(m.SvcSpent)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAgentwallet(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAgentwallet
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DelegationProof) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAgentwallet
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DelegationProof: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DelegationProof: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tokens", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAgentwallet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthAgentwallet
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthAgentwallet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tokens = append(m.Tokens, make([]byte, postIndex-iNdEx))
			copy(m.Tokens[len(m.Tokens)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DelegRef", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAgentwallet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthAgentwallet
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthAgentwallet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DelegRef = append(m.DelegRef[:0], dAtA[iNdEx:postIndex]...)
			if m.DelegRef == nil {
				m.DelegRef = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAgentwallet(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAgentwallet
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DelegatedOrderRef) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAgentwallet
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DelegatedOrderRef: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DelegatedOrderRef: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RootId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAgentwallet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthAgentwallet
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthAgentwallet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RootId = append(m.RootId[:0], dAtA[iNdEx:postIndex]...)
			if m.RootId == nil {
				m.RootId = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenChainHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAgentwallet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthAgentwallet
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthAgentwallet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TokenChainHash = append(m.TokenChainHash[:0], dAtA[iNdEx:postIndex]...)
			if m.TokenChainHash == nil {
				m.TokenChainHash = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExecutorAgentId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAgentwallet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAgentwallet
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAgentwallet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ExecutorAgentId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAgentwallet(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAgentwallet
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAgentwallet(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAgentwallet
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAgentwallet
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAgentwallet
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthAgentwallet
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupAgentwallet
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthAgentwallet
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthAgentwallet        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAgentwallet          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupAgentwallet = fmt.Errorf("proto: unexpected end of group")
)
