// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dydxprotocol/agentwallet/params.proto

package chainmsgs

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params is the governance-controlled configuration of `x/agentwallet`.
//
// These are chain-wide ceilings applied on top of whatever an individual
// delegation grants, so the stricter of the two always wins. A user can be more
// cautious than the chain requires, never less.
type Params struct {
	// Longest credential chain the chain will verify, whatever a delegation's
	// own max_depth says.
	//
	// Each hop costs a signature verification, so this bounds the work an
	// attacker can force with one transaction as much as it bounds delegation
	// topology.
	MaxDelegationDepth uint32 `protobuf:"varint,1,opt,name=max_delegation_depth,json=maxDelegationDepth,proto3" json:"max_delegation_depth,omitempty"`
	// Longest validity window any single credential may carry.
	//
	// Revocation is immediate on chain but takes until expiry to reach holders
	// who are only checking signatures, so this is the upper bound on how long a
	// revoked credential can still look valid off chain.
	MaxTokenTtlSeconds uint32 `protobuf:"varint,2,opt,name=max_token_ttl_seconds,json=maxTokenTtlSeconds,proto3" json:"max_token_ttl_seconds,omitempty"`
	// Maximum tokens accepted in one DelegationProof. Bounds decoding work
	// before depth is even known.
	MaxProofTokens uint32 `protobuf:"varint,3,opt,name=max_proof_tokens,json=maxProofTokens,proto3" json:"max_proof_tokens,omitempty"`
	// Blocks a consumed nonce is retained before pruning.
	//
	// Must exceed max_token_ttl_seconds in block terms: a nonce forgotten while
	// its credential is still inside its validity window would let that
	// credential be replayed.
	NonceRetentionBlocks uint32 `protobuf:"varint,4,opt,name=nonce_retention_blocks,json=nonceRetentionBlocks,proto3" json:"nonce_retention_blocks,omitempty"`
	// Maximum delegations one account may hold open, bounding the state a single
	// user can create.
	MaxDelegationsPerAccount uint32 `protobuf:"varint,5,opt,name=max_delegations_per_account,json=maxDelegationsPerAccount,proto3" json:"max_delegations_per_account,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_87327a2fb92c90bc, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetMaxDelegationDepth() uint32 {
	if m != nil {
		return m.MaxDelegationDepth
	}
	return 0
}

func (m *Params) GetMaxTokenTtlSeconds() uint32 {
	if m != nil {
		return m.MaxTokenTtlSeconds
	}
	return 0
}

func (m *Params) GetMaxProofTokens() uint32 {
	if m != nil {
		return m.MaxProofTokens
	}
	return 0
}

func (m *Params) GetNonceRetentionBlocks() uint32 {
	if m != nil {
		return m.NonceRetentionBlocks
	}
	return 0
}

func (m *Params) GetMaxDelegationsPerAccount() uint32 {
	if m != nil {
		return m.MaxDelegationsPerAccount
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "dydxprotocol.agentwallet.Params")
}

func init() {
	proto.RegisterFile("dydxprotocol/agentwallet/params.proto", fileDescriptor_87327a2fb92c90bc)
}

var fileDescriptor_87327a2fb92c90bc = []byte{
	// 301 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x40, 0xbb, 0x55, 0x7b, 0x08, 0x28, 0x12, 0xaa, 0x04, 0x84, 0x45, 0x04, 0xa1, 0x17, 0xbb,
	0x8a, 0xbd, 0xf6, 0x60, 0xe9, 0x07, 0x94, 0x5a, 0x10, 0xbc, 0x84, 0x34, 0x3b, 0xb6, 0xa5, 0xd9,
	0xcc, 0x92, 0x4c, 0x75, 0xfb, 0x0f, 0x1e, 0xfc, 0x2c, 0x8f, 0x3d, 0x7a, 0x94, 0xf6, 0x47, 0x64,
	0x53, 0x5c, 0xba, 0xd7, 0x79, 0xef, 0x41, 0x26, 0xc3, 0x6e, 0xd3, 0x75, 0x5a, 0xe4, 0x0e, 0x09,
	0x35, 0x9a, 0x44, 0xcd, 0xc0, 0xd2, 0x87, 0x32, 0x06, 0x28, 0xc9, 0x95, 0x53, 0x99, 0xef, 0x06,
	0xc6, 0xc5, 0xa1, 0xd6, 0x3d, 0xd0, 0x6e, 0x3e, 0x9b, 0xac, 0x35, 0x0a, 0x2a, 0xbf, 0x67, 0xed,
	0x4c, 0x15, 0x32, 0x05, 0x03, 0x33, 0x45, 0x0b, 0xb4, 0x32, 0x85, 0x9c, 0xe6, 0x22, 0xba, 0x8e,
	0x3a, 0xa7, 0x63, 0x9e, 0xa9, 0x62, 0x58, 0xa1, 0x61, 0x49, 0xf8, 0x03, 0xbb, 0x28, 0x0b, 0xc2,
	0x25, 0x58, 0x49, 0x64, 0xa4, 0x07, 0x8d, 0x36, 0xf5, 0xa2, 0x59, 0x25, 0x93, 0x92, 0x4d, 0xc8,
	0x3c, 0xef, 0x09, 0xef, 0xb0, 0xf3, 0x32, 0xc9, 0x1d, 0xe2, 0xdb, 0x3e, 0xf4, 0xe2, 0x28, 0xd8,
	0x67, 0x99, 0x2a, 0x46, 0xe5, 0x38, 0x24, 0x9e, 0xf7, 0xd8, 0xa5, 0x45, 0xab, 0x41, 0x3a, 0x20,
	0xb0, 0xe1, 0x3d, 0x53, 0x83, 0x7a, 0xe9, 0xc5, 0x71, 0xf0, 0xdb, 0x81, 0x8e, 0xff, 0xe1, 0x20,
	0x30, 0xde, 0x67, 0x57, 0xf5, 0x25, 0xbc, 0xcc, 0xc1, 0x49, 0xa5, 0x35, 0xae, 0x2c, 0x89, 0x93,
	0x90, 0x8a, 0xda, 0x2e, 0x7e, 0x04, 0xee, 0x69, 0xcf, 0x07, 0x2f, 0xdf, 0xdb, 0x38, 0xda, 0x6c,
	0xe3, 0xe8, 0x77, 0x1b, 0x47, 0x5f, 0xbb, 0xb8, 0xb1, 0xd9, 0xc5, 0x8d, 0x9f, 0x5d, 0xdc, 0x78,
	0xed, 0xcf, 0x16, 0x34, 0x5f, 0x4d, 0xbb, 0x1a, 0xb3, 0xa4, 0xf6, 0xe9, 0xef, 0xbd, 0x3b, 0x3d,
	0x57, 0x0b, 0x9b, 0x54, 0x93, 0xa2, 0x76, 0x08, 0x5a, 0xe7, 0xe0, 0xa7, 0xad, 0x40, 0x1f, 0xff,
	0x02, 0x00, 0x00, 0xff, 0xff, 0x0c, 0xf8, 0xe7, 0x14, 0xb1, 0x01, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MaxDelegationsPerAccount != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxDelegationsPerAccount))
		i--
		dAtA[i] = 0x28
	}
	if m.NonceRetentionBlocks != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.NonceRetentionBlocks))
		i--
		dAtA[i] = 0x20
	}
	if m.MaxProofTokens != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxProofTokens))
		i--
		dAtA[i] = 0x18
	}
	if m.MaxTokenTtlSeconds != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxTokenTtlSeconds))
		i--
		dAtA[i] = 0x10
	}
	if m.MaxDelegationDepth != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxDelegationDepth))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MaxDelegationDepth != 0 {
		n += 1 + sovParams(uint64(m.MaxDelegationDepth))
	}
	if m.MaxTokenTtlSeconds != 0 {
		n += 1 + sovParams(uint64(m.MaxTokenTtlSeconds))
	}
	if m.MaxProofTokens != 0 {
		n += 1 + sovParams(uint64(m.MaxProofTokens))
	}
	if m.NonceRetentionBlocks != 0 {
		n += 1 + sovParams(uint64(m.NonceRetentionBlocks))
	}
	if m.MaxDelegationsPerAccount != 0 {
		n += 1 + sovParams(uint64(m.MaxDelegationsPerAccount))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxDelegationDepth", wireType)
			}
			m.MaxDelegationDepth = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxDelegationDepth |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxTokenTtlSeconds", wireType)
			}
			m.MaxTokenTtlSeconds = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxTokenTtlSeconds |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxProofTokens", wireType)
			}
			m.MaxProofTokens = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxProofTokens |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NonceRetentionBlocks", wireType)
			}
			m.NonceRetentionBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NonceRetentionBlocks |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxDelegationsPerAccount", wireType)
			}
			m.MaxDelegationsPerAccount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxDelegationsPerAccount |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
