// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dydxprotocol/settlement/params.proto

package settlement

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params is the governance-controlled configuration of `x/settlement`.
type Params struct {
	// Fraction of a claim diverted to the treasury when an agent withdraws, in
	// [0, 1]. Charged at claim time so an order that ends in refund pays no
	// commission on work that was never compensated.
	MarketplaceCommission cosmossdk_io_math.LegacyDec `protobuf:"bytes,1,opt,name=marketplace_commission,json=marketplaceCommission,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"marketplace_commission"`
	// Fraction of the cap charged to the opener on top of the escrow when an
	// order is opened, in [0, 1]. Goes to the treasury immediately and is not
	// refundable — it prices the escrow service itself, not the work.
	PaymentFee cosmossdk_io_math.LegacyDec `protobuf:"bytes,2,opt,name=payment_fee,json=paymentFee,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"payment_fee"`
	// Maximum orders one account may hold open, bounding the state a single
	// user can create.
	MaxOpenSettlementsPerAccount uint32 `protobuf:"varint,3,opt,name=max_open_settlements_per_account,json=maxOpenSettlementsPerAccount,proto3" json:"max_open_settlements_per_account,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf2dfeae36d34642, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetMaxOpenSettlementsPerAccount() uint32 {
	if m != nil {
		return m.MaxOpenSettlementsPerAccount
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "dydxprotocol.settlement.Params")
}

func init() {
	proto.RegisterFile("dydxprotocol/settlement/params.proto", fileDescriptor_bf2dfeae36d34642)
}

var fileDescriptor_bf2dfeae36d34642 = []byte{
	// 341 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x91, 0xbd, 0x4a, 0x03, 0x41,
	0x14, 0x85, 0x77, 0x23, 0x04, 0x5c, 0xb1, 0x70, 0xf1, 0x27, 0x46, 0xd9, 0x04, 0xb1, 0x08, 0x42,
	0x76, 0x0a, 0xc5, 0xca, 0xc6, 0x18, 0x52, 0x09, 0x86, 0x08, 0x0a, 0x36, 0xc3, 0x64, 0x72, 0xdd,
	0x2c, 0xc9, 0xcc, 0x1d, 0x76, 0x26, 0xb2, 0xfb, 0x16, 0x96, 0x3e, 0x82, 0xa5, 0x85, 0x0f, 0x91,
	0x32, 0x58, 0x89, 0x45, 0x90, 0xa4, 0xf0, 0x35, 0x24, 0xbb, 0x21, 0x89, 0xb5, 0xcd, 0x30, 0xf7,
	0x9c, 0x8f, 0x73, 0x98, 0xb9, 0xce, 0x71, 0x27, 0xe9, 0xc4, 0x2a, 0x42, 0x83, 0x1c, 0xfb, 0x44,
	0x83, 0x31, 0x7d, 0x10, 0x20, 0x0d, 0x51, 0x2c, 0x62, 0x42, 0xfb, 0xa9, 0xe5, 0xee, 0xad, 0x52,
	0xfe, 0x92, 0x2a, 0x6e, 0x31, 0x11, 0x4a, 0x24, 0xe9, 0x99, 0xb1, 0xc5, 0x7d, 0x8e, 0x5a, 0xa0,
	0xa6, 0xe9, 0x44, 0xb2, 0x61, 0x6e, 0x6d, 0x07, 0x18, 0x60, 0xa6, 0xcf, 0x6e, 0x99, 0x7a, 0xf4,
	0x92, 0x73, 0xf2, 0xcd, 0xb4, 0xcd, 0x15, 0xce, 0xae, 0x60, 0x51, 0x0f, 0x8c, 0xea, 0x33, 0x0e,
	0x94, 0xa3, 0x10, 0xa1, 0xd6, 0x21, 0xca, 0x82, 0x5d, 0xb6, 0x2b, 0xeb, 0xb5, 0xf3, 0xe1, 0xb8,
	0x64, 0x7d, 0x8d, 0x4b, 0x07, 0x59, 0xac, 0xee, 0xf4, 0xfc, 0x10, 0x89, 0x60, 0xa6, 0xeb, 0x5f,
	0x43, 0xc0, 0x78, 0x52, 0x07, 0xfe, 0xf1, 0x5e, 0x75, 0xe6, 0xad, 0x75, 0xe0, 0xaf, 0x3f, 0x6f,
	0x27, 0x76, 0x6b, 0x67, 0x25, 0xf5, 0x6a, 0x11, 0xea, 0xde, 0x3b, 0x1b, 0x8a, 0x25, 0xb3, 0x87,
	0xd0, 0x47, 0x80, 0x42, 0xee, 0x5f, 0x1d, 0xce, 0x3c, 0xaa, 0x01, 0xe0, 0x36, 0x9c, 0xb2, 0x60,
	0x31, 0x45, 0x05, 0x92, 0x2e, 0x7f, 0x4b, 0x53, 0x05, 0x11, 0x65, 0x9c, 0xe3, 0x40, 0x9a, 0xc2,
	0x5a, 0xd9, 0xae, 0x6c, 0xb6, 0x0e, 0x05, 0x8b, 0x6f, 0x14, 0xc8, 0xdb, 0x25, 0xd5, 0x84, 0xe8,
	0x32, 0x63, 0x6a, 0x77, 0xc3, 0x89, 0x67, 0x8f, 0x26, 0x9e, 0xfd, 0x3d, 0xf1, 0xec, 0xe7, 0xa9,
	0x67, 0x8d, 0xa6, 0x9e, 0xf5, 0x39, 0xf5, 0xac, 0x87, 0x8b, 0x20, 0x34, 0xdd, 0x41, 0xdb, 0xe7,
	0x28, 0xc8, 0x9f, 0x15, 0x3e, 0x9d, 0x55, 0x79, 0x97, 0x85, 0x92, 0x2c, 0x94, 0x78, 0x75, 0xad,
	0x26, 0x51, 0xa0, 0xdb, 0xf9, 0xd4, 0x3c, 0xfd, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x75, 0xf2, 0x46,
	0x2d, 0xfe, 0x01, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MaxOpenSettlementsPerAccount != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxOpenSettlementsPerAccount))
		i--
		dAtA[i] = 0x18
	}
	{
		size := m.PaymentFee.Size()
		i -= size
		if _, err := m.PaymentFee.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.MarketplaceCommission.Size()
		i -= size
		if _, err := m.MarketplaceCommission.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.MarketplaceCommission.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.PaymentFee.Size()
	n += 1 + l + sovParams(uint64(l))
	if m.MaxOpenSettlementsPerAccount != 0 {
		n += 1 + sovParams(uint64(m.MaxOpenSettlementsPerAccount))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MarketplaceCommission", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MarketplaceCommission.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PaymentFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PaymentFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxOpenSettlementsPerAccount", wireType)
			}
			m.MaxOpenSettlementsPerAccount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxOpenSettlementsPerAccount |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
