// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dydxprotocol/settlement/settlement.proto

package settlement

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// SettlementStatus is the lifecycle state of a settlement order.
type SettlementStatus int32

const (
	// Unspecified. Never stored.
	SettlementStatus_SETTLEMENT_STATUS_UNSPECIFIED SettlementStatus = 0
	// Open: escrow is held and agents may record spend against the cap.
	SettlementStatus_SETTLEMENT_STATUS_OPEN SettlementStatus = 1
	// Settled: closed normally. Unspent escrow went back to the opener;
	// recorded claimables survive for the agents to claim.
	SettlementStatus_SETTLEMENT_STATUS_SETTLED SettlementStatus = 2
	// Refunded: closed by full refund. Unclaimed escrow went back to the
	// opener and every outstanding claimable was zeroed.
	SettlementStatus_SETTLEMENT_STATUS_REFUNDED SettlementStatus = 3
)

var SettlementStatus_name = map[int32]string{
	0: "SETTLEMENT_STATUS_UNSPECIFIED",
	1: "SETTLEMENT_STATUS_OPEN",
	2: "SETTLEMENT_STATUS_SETTLED",
	3: "SETTLEMENT_STATUS_REFUNDED",
}

var SettlementStatus_value = map[string]int32{
	"SETTLEMENT_STATUS_UNSPECIFIED": 0,
	"SETTLEMENT_STATUS_OPEN":        1,
	"SETTLEMENT_STATUS_SETTLED":     2,
	"SETTLEMENT_STATUS_REFUNDED":    3,
}

func (x SettlementStatus) String() string {
	return proto.EnumName(SettlementStatus_name, int32(x))
}

func (SettlementStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7e574d46aed5fd29, []int{0}
}

// SettlementOrder escrows an upper-bound prepayment for a delegated task.
//
// The order is the money container an SVP-DT credential can bind to via its
// settlement caveat: agents doing the work record spend against the cap and
// accrue claimables, and whatever was not spent goes back to the user. Orders
// are never deleted — a terminal order is the audit record of who was paid
// for what.
type SettlementOrder struct {
	// Deterministic 32-byte id, derived from the opener and a per-opener
	// sequence. Derived rather than random because state transitions must be
	// reproducible across validators.
	Id []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Account that escrowed the cap and receives every refund. Every
	// settlement message is authorised against this account.
	Opener string `protobuf:"bytes,2,opt,name=opener,proto3" json:"opener,omitempty"`
	// The escrowed upper bound. Recorded spend can never exceed it — the
	// gas-limit property of the prepayment.
	Cap types.Coin `protobuf:"bytes,3,opt,name=cap,proto3" json:"cap"`
	// PaymentFee charged on top of the cap when the order was opened. Kept for
	// the record; it went to the treasury immediately and is never refunded.
	FeePaid types.Coin `protobuf:"bytes,4,opt,name=fee_paid,json=feePaid,proto3" json:"fee_paid"`
	// Running total of recorded spend across all agents.
	TotalRecorded types.Coin `protobuf:"bytes,5,opt,name=total_recorded,json=totalRecorded,proto3" json:"total_recorded"`
	// Running total already paid out through claims (gross, before the
	// marketplace commission split).
	TotalClaimed types.Coin `protobuf:"bytes,6,opt,name=total_claimed,json=totalClaimed,proto3" json:"total_claimed"`
	// Amount returned to the opener when the order left the OPEN state.
	Refunded types.Coin `protobuf:"bytes,7,opt,name=refunded,proto3" json:"refunded"`
	// Lifecycle state.
	Status SettlementStatus `protobuf:"varint,8,opt,name=status,proto3,enum=dydxprotocol.settlement.SettlementStatus" json:"status,omitempty"`
	// Root delegation this order was opened under, when it was opened through
	// a delegated execution; empty when the opener signed directly. Feeds
	// attribution and off-chain reputation.
	RootDelegationId []byte `protobuf:"bytes,9,opt,name=root_delegation_id,json=rootDelegationId,proto3" json:"root_delegation_id,omitempty"`
	// Height at which the order was opened.
	CreatedAtHeight uint64 `protobuf:"varint,10,opt,name=created_at_height,json=createdAtHeight,proto3" json:"created_at_height,omitempty"`
	// Free-form task reference, bounded length. For correlating the order with
	// the off-chain task (e.g. an A2A task id); the chain does not interpret it.
	Memo string `protobuf:"bytes,11,opt,name=memo,proto3" json:"memo,omitempty"`
}

func (m *SettlementOrder) Reset()         { *m = SettlementOrder{} }
func (m *SettlementOrder) String() string { return proto.CompactTextString(m) }
func (*SettlementOrder) ProtoMessage()    {}
func (*SettlementOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e574d46aed5fd29, []int{0}
}
func (m *SettlementOrder) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SettlementOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SettlementOrder.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SettlementOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SettlementOrder.Merge(m, src)
}
func (m *SettlementOrder) XXX_Size() int {
	return m.Size()
}
func (m *SettlementOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_SettlementOrder.DiscardUnknown(m)
}

var xxx_messageInfo_SettlementOrder proto.InternalMessageInfo

func (m *SettlementOrder) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *SettlementOrder) GetOpener() string {
	if m != nil {
		return m.Opener
	}
	return ""
}

func (m *SettlementOrder) GetCap() types.Coin {
	if m != nil {
		return m.Cap
	}
	return types.Coin{}
}

func (m *SettlementOrder) GetFeePaid() types.Coin {
	if m != nil {
		return m.FeePaid
	}
	return types.Coin{}
}

func (m *SettlementOrder) GetTotalRecorded() types.Coin {
	if m != nil {
		return m.TotalRecorded
	}
	return types.Coin{}
}

func (m *SettlementOrder) GetTotalClaimed() types.Coin {
	if m != nil {
		return m.TotalClaimed
	}
	return types.Coin{}
}

func (m *SettlementOrder) GetRefunded() types.Coin {
	if m != nil {
		return m.Refunded
	}
	return types.Coin{}
}

func (m *SettlementOrder) GetStatus() SettlementStatus {
	if m != nil {
		return m.Status
	}
	return SettlementStatus_SETTLEMENT_STATUS_UNSPECIFIED
}

func (m *SettlementOrder) GetRootDelegationId() []byte {
	if m != nil {
		return m.RootDelegationId
	}
	return nil
}

func (m *SettlementOrder) GetCreatedAtHeight() uint64 {
	if m != nil {
		return m.CreatedAtHeight
	}
	return 0
}

func (m *SettlementOrder) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

// Claimable is one agent's unclaimed accrual against one settlement order.
type Claimable struct {
	// Order the accrual belongs to.
	SettlementId []byte `protobuf:"bytes,1,opt,name=settlement_id,json=settlementId,proto3" json:"settlement_id,omitempty"`
	// DID of the agent owed the amount.
	AgentId string `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Unclaimed amount. A claim always pays the whole amount and zeroes it —
	// there is no partial-claim field for a caller to overstate.
	Amount types.Coin `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount"`
}

func (m *Claimable) Reset()         { *m = Claimable{} }
func (m *Claimable) String() string { return proto.CompactTextString(m) }
func (*Claimable) ProtoMessage()    {}
func (*Claimable) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e574d46aed5fd29, []int{1}
}
func (m *Claimable) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Claimable) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Claimable.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Claimable) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Claimable.Merge(m, src)
}
func (m *Claimable) XXX_Size() int {
	return m.Size()
}
func (m *Claimable) XXX_DiscardUnknown() {
	xxx_messageInfo_Claimable.DiscardUnknown(m)
}

var xxx_messageInfo_Claimable proto.InternalMessageInfo

func (m *Claimable) GetSettlementId() []byte {
	if m != nil {
		return m.SettlementId
	}
	return nil
}

func (m *Claimable) GetAgentId() string {
	if m != nil {
		return m.AgentId
	}
	return ""
}

func (m *Claimable) GetAmount() types.Coin {
	if m != nil {
		return m.Amount
	}
	return types.Coin{}
}

func init() {
	proto.RegisterEnum("dydxprotocol.settlement.SettlementStatus", SettlementStatus_name, SettlementStatus_value)
	proto.RegisterType((*SettlementOrder)(nil), "dydxprotocol.settlement.SettlementOrder")
	proto.RegisterType((*Claimable)(nil), "dydxprotocol.settlement.Claimable")
}

func init() {
	proto.RegisterFile("dydxprotocol/settlement/settlement.proto", fileDescriptor_7e574d46aed5fd29)
}

var fileDescriptor_7e574d46aed5fd29 = []byte{
	// 590 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0xb3, 0x69, 0x48, 0xd3, 0xed, 0xbf, 0xb0, 0xaa, 0xc0, 0x89, 0x54, 0x13, 0xca, 0xc5,
	0x54, 0xd4, 0xa6, 0x05, 0x09, 0x09, 0xb8, 0xa4, 0xb5, 0x2b, 0x22, 0x41, 0x5a, 0xd9, 0x29, 0x07,
	0x2e, 0xd6, 0xc6, 0x3b, 0x75, 0x56, 0xb2, 0xbd, 0x91, 0xbd, 0xa9, 0xda, 0x3b, 0x0f, 0xd0, 0x87,
	0xe1, 0xcc, 0xb9, 0xc7, 0x8a, 0x13, 0x27, 0x84, 0xda, 0x17, 0x41, 0x5e, 0x5b, 0x49, 0xa1, 0x42,
	0xca, 0x6d, 0xf6, 0xfb, 0x7d, 0xdf, 0x64, 0xe2, 0x1d, 0x2d, 0x36, 0xd8, 0x05, 0x3b, 0x1f, 0xa7,
	0x42, 0x8a, 0x40, 0x44, 0x56, 0x06, 0x52, 0x46, 0x10, 0x43, 0x22, 0xef, 0x94, 0xa6, 0xc2, 0xe4,
	0xf1, 0x5d, 0xa7, 0x39, 0xc3, 0xed, 0x56, 0x20, 0xb2, 0x58, 0x64, 0xbe, 0x62, 0x56, 0x71, 0x28,
	0x32, 0xed, 0x8d, 0x50, 0x84, 0xa2, 0xd0, 0xf3, 0xaa, 0x54, 0xf5, 0xc2, 0x63, 0x0d, 0x69, 0x06,
	0xd6, 0xd9, 0xee, 0x10, 0x24, 0xdd, 0xb5, 0x02, 0xc1, 0x93, 0x82, 0x6f, 0x7d, 0xaf, 0xe1, 0x75,
	0x6f, 0xda, 0xff, 0x28, 0x65, 0x90, 0x92, 0x35, 0x5c, 0xe5, 0x4c, 0x43, 0x1d, 0x64, 0xac, 0xb8,
	0x55, 0xce, 0xc8, 0x4b, 0x5c, 0x17, 0x63, 0x48, 0x20, 0xd5, 0xaa, 0x1d, 0x64, 0x2c, 0xed, 0x6b,
	0x3f, 0xbe, 0xed, 0x6c, 0x94, 0xbf, 0xdd, 0x65, 0x2c, 0x85, 0x2c, 0xf3, 0x64, 0xca, 0x93, 0xd0,
	0x2d, 0x7d, 0x64, 0x17, 0x2f, 0x04, 0x74, 0xac, 0x2d, 0x74, 0x90, 0xb1, 0xbc, 0xd7, 0x32, 0x4b,
	0x6f, 0x3e, 0x83, 0x59, 0xce, 0x60, 0x1e, 0x08, 0x9e, 0xec, 0xd7, 0xae, 0x7e, 0x3d, 0xa9, 0xb8,
	0xb9, 0x97, 0xbc, 0xc5, 0x8d, 0x53, 0x00, 0x7f, 0x4c, 0x39, 0xd3, 0x6a, 0xf3, 0xe5, 0x16, 0x4f,
	0x01, 0x8e, 0x29, 0x67, 0xe4, 0x10, 0xaf, 0x49, 0x21, 0x69, 0xe4, 0xa7, 0x10, 0x88, 0x94, 0x01,
	0xd3, 0x1e, 0xcc, 0xd7, 0x61, 0x55, 0xc5, 0xdc, 0x32, 0x45, 0x6c, 0x5c, 0x08, 0x7e, 0x10, 0x51,
	0x1e, 0x03, 0xd3, 0xea, 0xf3, 0xb5, 0x59, 0x51, 0xa9, 0x83, 0x22, 0x44, 0xde, 0xe1, 0x46, 0x0a,
	0xa7, 0x93, 0x24, 0x9f, 0x63, 0x71, 0xbe, 0x06, 0xd3, 0x00, 0xe9, 0xe2, 0x7a, 0x26, 0xa9, 0x9c,
	0x64, 0x5a, 0xa3, 0x83, 0x8c, 0xb5, 0xbd, 0xe7, 0xe6, 0x7f, 0x56, 0xc1, 0x9c, 0xdd, 0x9a, 0xa7,
	0x02, 0x6e, 0x19, 0x24, 0x2f, 0x30, 0x49, 0x85, 0x90, 0x3e, 0x83, 0x08, 0x42, 0x2a, 0xb9, 0x48,
	0x7c, 0xce, 0xb4, 0x25, 0x75, 0x9d, 0xcd, 0x9c, 0xd8, 0x53, 0xd0, 0x63, 0x64, 0x1b, 0x3f, 0x0c,
	0x52, 0xa0, 0x12, 0x98, 0x4f, 0xa5, 0x3f, 0x02, 0x1e, 0x8e, 0xa4, 0x86, 0x3b, 0xc8, 0xa8, 0xb9,
	0xeb, 0x25, 0xe8, 0xca, 0x0f, 0x4a, 0x26, 0x04, 0xd7, 0x62, 0x88, 0x85, 0xb6, 0x9c, 0xaf, 0x81,
	0xab, 0xea, 0xad, 0xaf, 0x08, 0x2f, 0xa9, 0x7f, 0x4e, 0x87, 0x11, 0x90, 0x67, 0x78, 0x75, 0x36,
	0xa2, 0x3f, 0xdd, 0xa2, 0x95, 0x99, 0xd8, 0x63, 0xa4, 0x85, 0x1b, 0x34, 0x2c, 0xb9, 0xda, 0x28,
	0x77, 0x51, 0x9d, 0x7b, 0x8c, 0xbc, 0xc1, 0x75, 0x1a, 0x8b, 0x49, 0x22, 0xe7, 0xdd, 0x9d, 0xd2,
	0xbe, 0x7d, 0x89, 0x70, 0xf3, 0xdf, 0x2f, 0x42, 0x9e, 0xe2, 0x4d, 0xcf, 0x19, 0x0c, 0x3e, 0x3a,
	0x9f, 0x9c, 0xfe, 0xc0, 0xf7, 0x06, 0xdd, 0xc1, 0x89, 0xe7, 0x9f, 0xf4, 0xbd, 0x63, 0xe7, 0xa0,
	0x77, 0xd8, 0x73, 0xec, 0x66, 0x85, 0xb4, 0xf1, 0xa3, 0xfb, 0x96, 0xa3, 0x63, 0xa7, 0xdf, 0x44,
	0x64, 0x13, 0xb7, 0xee, 0xb3, 0x42, 0xb1, 0x9b, 0x55, 0xa2, 0xe3, 0xf6, 0x7d, 0xec, 0x3a, 0x87,
	0x27, 0x7d, 0xdb, 0xb1, 0x9b, 0x0b, 0xfb, 0x9f, 0xaf, 0x6e, 0x74, 0x74, 0x7d, 0xa3, 0xa3, 0xdf,
	0x37, 0x3a, 0xba, 0xbc, 0xd5, 0x2b, 0xd7, 0xb7, 0x7a, 0xe5, 0xe7, 0xad, 0x5e, 0xf9, 0xf2, 0x3e,
	0xe4, 0x72, 0x34, 0x19, 0x9a, 0x81, 0x88, 0xad, 0xbf, 0xde, 0x84, 0xb3, 0xd7, 0x3b, 0xc1, 0x88,
	0xf2, 0xc4, 0x9a, 0x2a, 0xe7, 0x77, 0xdf, 0x09, 0x79, 0x31, 0x86, 0x6c, 0x58, 0x57, 0xf0, 0xd5,
	0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x36, 0x5c, 0xf8, 0x65, 0x4f, 0x04, 0x00, 0x00,
}

func (m *SettlementOrder) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SettlementOrder) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SettlementOrder) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Memo) > 0 {
		i -= len(m.Memo)
		copy(dAtA[i:], m.Memo)
		i = encodeVarintSettlement(dAtA, i, uint64(len(m.Memo)))
		i--
		dAtA[i] = 0x5a
	}
	if m.CreatedAtHeight != 0 {
		i = encodeVarintSettlement(dAtA, i, uint64(m.CreatedAtHeight))
		i--
		dAtA[i] = 0x50
	}
	if len(m.RootDelegationId) > 0 {
		i -= len(m.RootDelegationId)
		copy(dAtA[i:], m.RootDelegationId)
		i = encodeVarintSettlement(dAtA, i, uint64(len(m.RootDelegationId)))
		i--
		dAtA[i] = 0x4a
	}
	if m.Status != 0 {
		i = encodeVarintSettlement(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x40
	}
	{
		size, err := m.Refunded.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintSettlement(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	{
		size, err := m.TotalClaimed.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintSettlement(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size, err := m.TotalRecorded.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintSettlement(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size, err := m.FeePaid.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintSettlement(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size, err := m.Cap.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintSettlement(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.Opener) > 0 {
		i -= len(m.Opener)
		copy(dAtA[i:], m.Opener)
		i = encodeVarintSettlement(dAtA, i, uint64(len(m.Opener)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintSettlement(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Claimable) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Claimable) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Claimable) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Amount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintSettlement(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.AgentId) > 0 {
		i -= len(m.AgentId)
		copy(dAtA[i:], m.AgentId)
		i = encodeVarintSettlement(dAtA, i, uint64(len(m.AgentId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.SettlementId) > 0 {
		i -= len(m.SettlementId)
		copy(dAtA[i:], m.SettlementId)
		i = encodeVarintSettlement(dAtA, i, uint64(len(m.SettlementId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintSettlement(dAtA []byte, offset int, v uint64) int {
	offset -= sovSettlement(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *SettlementOrder) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovSettlement(uint64(l))
	}
	l = len(m.Opener)
	if l > 0 {
		n += 1 + l + sovSettlement(uint64(l))
	}
	l = m.Cap.Size()
	n += 1 + l + sovSettlement(uint64(l))
	l = m.FeePaid.Size()
	n += 1 + l + sovSettlement(uint64(l))
	l = m.TotalRecorded.Size()
	n += 1 + l + sovSettlement(uint64(l))
	l = m.TotalClaimed.Size()
	n += 1 + l + sovSettlement(uint64(l))
	l = m.Refunded.Size()
	n += 1 + l + sovSettlement(uint64(l))
	if m.Status != 0 {
		n += 1 + sovSettlement(uint64(m.Status))
	}
	l = len(m.RootDelegationId)
	if l > 0 {
		n += 1 + l + sovSettlement(uint64(l))
	}
	if m.CreatedAtHeight != 0 {
		n += 1 + sovSettlement(uint64(m.CreatedAtHeight))
	}
	l = len(m.Memo)
	if l > 0 {
		n += 1 + l + sovSettlement(uint64(l))
	}
	return n
}

func (m *Claimable) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SettlementId)
	if l > 0 {
		n += 1 + l + sovSettlement(uint64(l))
	}
	l = len(m.AgentId)
	if l > 0 {
		n += 1 + l + sovSettlement(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovSettlement(uint64(l))
	return n
}

func sovSettlement(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSettlement(x uint64) (n int) {
	return sovSettlement(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SettlementOrder) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSettlement
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SettlementOrder: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SettlementOrder: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettlement
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSettlement
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSettlement
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = append(m.Id[:0], dAtA[iNdEx:postIndex]...)
			if m.Id == nil {
				m.Id = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Opener", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettlement
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSettlement
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSettlement
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Opener = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cap", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettlement
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSettlement
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSettlement
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Cap.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeePaid", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettlement
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSettlement
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSettlement
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.FeePaid.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalRecorded", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettlement
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSettlement
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSettlement
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalRecorded.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalClaimed", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettlement
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSettlement
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSettlement
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalClaimed.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Refunded", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettlement
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSettlement
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSettlement
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Refunded.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettlement
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= SettlementStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RootDelegationId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettlement
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSettlement
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSettlement
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RootDelegationId = append(m.RootDelegationId[:0], dAtA[iNdEx:postIndex]...)
			if m.RootDelegationId == nil {
				m.RootDelegationId = []byte{}
			}
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAtHeight", wireType)
			}
			m.CreatedAtHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettlement
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAtHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Memo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettlement
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSettlement
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSettlement
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Memo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSettlement(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSettlement
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Claimable) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSettlement
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Claimable: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Claimable: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SettlementId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettlement
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSettlement
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSettlement
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SettlementId = append(m.SettlementId[:0], dAtA[iNdEx:postIndex]...)
			if m.SettlementId == nil {
				m.SettlementId = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AgentId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettlement
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSettlement
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSettlement
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AgentId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettlement
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSettlement
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSettlement
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSettlement(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSettlement
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSettlement(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSettlement
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSettlement
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSettlement
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSettlement
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSettlement
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSettlement
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSettlement        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSettlement          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSettlement = fmt.Errorf("proto: unexpected end of group")
)
