// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dydxprotocol/settlement/tx.proto

package settlement

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgOpenSettlement escrows an upper-bound prepayment for a delegated task.
//
// The cap plus cap×PaymentFee is taken from the opener: the cap into escrow,
// the fee to the treasury. Delegatable — an orchestrating agent may open an
// order on the user's root delegation, in which case the opener is the
// delegation's principal and the cap is priced against its service budget.
type MsgOpenSettlement struct {
	// Account funding the escrow, and the principal every later settlement
	// message binds to.
	Opener string `protobuf:"bytes,1,opt,name=opener,proto3" json:"opener,omitempty"`
	// The escrowed upper bound on what the task may cost.
	Cap types.Coin `protobuf:"bytes,2,opt,name=cap,proto3" json:"cap"`
	// Free-form task reference, bounded length.
	Memo string `protobuf:"bytes,3,opt,name=memo,proto3" json:"memo,omitempty"`
}

func (m *MsgOpenSettlement) Reset()         { *m = MsgOpenSettlement{} }
func (m *MsgOpenSettlement) String() string { return proto.CompactTextString(m) }
func (*MsgOpenSettlement) ProtoMessage()    {}
func (*MsgOpenSettlement) Descriptor() ([]byte, []int) {
	return fileDescriptor_27434265999fa647, []int{0}
}
func (m *MsgOpenSettlement) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgOpenSettlement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgOpenSettlement.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgOpenSettlement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgOpenSettlement.Merge(m, src)
}
func (m *MsgOpenSettlement) XXX_Size() int {
	return m.Size()
}
func (m *MsgOpenSettlement) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgOpenSettlement.DiscardUnknown(m)
}

var xxx_messageInfo_MsgOpenSettlement proto.InternalMessageInfo

func (m *MsgOpenSettlement) GetOpener() string {
	if m != nil {
		return m.Opener
	}
	return ""
}

func (m *MsgOpenSettlement) GetCap() types.Coin {
	if m != nil {
		return m.Cap
	}
	return types.Coin{}
}

func (m *MsgOpenSettlement) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

// MsgOpenSettlementResponse is the OpenSettlement response type.
type MsgOpenSettlementResponse struct {
	// Id of the order just opened. Credentials bind to it via their settlement
	// caveat, and every later settlement message names it.
	Id []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgOpenSettlementResponse) Reset()         { *m = MsgOpenSettlementResponse{} }
func (m *MsgOpenSettlementResponse) String() string { return proto.CompactTextString(m) }
func (*MsgOpenSettlementResponse) ProtoMessage()    {}
func (*MsgOpenSettlementResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_27434265999fa647, []int{1}
}
func (m *MsgOpenSettlementResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgOpenSettlementResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgOpenSettlementResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgOpenSettlementResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgOpenSettlementResponse.Merge(m, src)
}
func (m *MsgOpenSettlementResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgOpenSettlementResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgOpenSettlementResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgOpenSettlementResponse proto.InternalMessageInfo

func (m *MsgOpenSettlementResponse) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

// MsgRecordSpend records actual spend against an open order.
//
// The signer is the opener — the account whose escrow is being consumed. An
// agent never signs this directly: it arrives wrapped in MsgAgentExecDelegated,
// where the agent's signature plus the credential chain substitute for the
// opener's, and the chain asserts the recorded agent is the executing agent.
type MsgRecordSpend struct {
	// The order's opener, whose escrow the spend consumes.
	Principal string `protobuf:"bytes,1,opt,name=principal,proto3" json:"principal,omitempty"`
	// Order being recorded against.
	SettlementId []byte `protobuf:"bytes,2,opt,name=settlement_id,json=settlementId,proto3" json:"settlement_id,omitempty"`
	// DID of the agent that did the work and accrues the claimable. When
	// executed delegated, must equal the executing agent.
	AgentId string `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Amount of the cap consumed. Same denom as the cap.
	Amount types.Coin `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount"`
}

func (m *MsgRecordSpend) Reset()         { *m = MsgRecordSpend{} }
func (m *MsgRecordSpend) String() string { return proto.CompactTextString(m) }
func (*MsgRecordSpend) ProtoMessage()    {}
func (*MsgRecordSpend) Descriptor() ([]byte, []int) {
	return fileDescriptor_27434265999fa647, []int{2}
}
func (m *MsgRecordSpend) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRecordSpend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRecordSpend.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRecordSpend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRecordSpend.Merge(m, src)
}
func (m *MsgRecordSpend) XXX_Size() int {
	return m.Size()
}
func (m *MsgRecordSpend) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRecordSpend.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRecordSpend proto.InternalMessageInfo

func (m *MsgRecordSpend) GetPrincipal() string {
	if m != nil {
		return m.Principal
	}
	return ""
}

func (m *MsgRecordSpend) GetSettlementId() []byte {
	if m != nil {
		return m.SettlementId
	}
	return nil
}

func (m *MsgRecordSpend) GetAgentId() string {
	if m != nil {
		return m.AgentId
	}
	return ""
}

func (m *MsgRecordSpend) GetAmount() types.Coin {
	if m != nil {
		return m.Amount
	}
	return types.Coin{}
}

// MsgRecordSpendResponse is the RecordSpend response type.
type MsgRecordSpendResponse struct {
	// Total recorded against the order after this message.
	TotalRecorded types.Coin `protobuf:"bytes,1,opt,name=total_recorded,json=totalRecorded,proto3" json:"total_recorded"`
}

func (m *MsgRecordSpendResponse) Reset()         { *m = MsgRecordSpendResponse{} }
func (m *MsgRecordSpendResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRecordSpendResponse) ProtoMessage()    {}
func (*MsgRecordSpendResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_27434265999fa647, []int{3}
}
func (m *MsgRecordSpendResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRecordSpendResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRecordSpendResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRecordSpendResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRecordSpendResponse.Merge(m, src)
}
func (m *MsgRecordSpendResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRecordSpendResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRecordSpendResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRecordSpendResponse proto.InternalMessageInfo

func (m *MsgRecordSpendResponse) GetTotalRecorded() types.Coin {
	if m != nil {
		return m.TotalRecorded
	}
	return types.Coin{}
}

// MsgSettle closes an order normally.
//
// The unrecorded remainder (cap − total_recorded) refunds to the opener and
// the order becomes SETTLED. Claimables survive: settling is the opener
// saying "the task is done", not "nobody gets paid".
type MsgSettle struct {
	// The order's opener.
	Opener string `protobuf:"bytes,1,opt,name=opener,proto3" json:"opener,omitempty"`
	// Order being settled.
	SettlementId []byte `protobuf:"bytes,2,opt,name=settlement_id,json=settlementId,proto3" json:"settlement_id,omitempty"`
}

func (m *MsgSettle) Reset()         { *m = MsgSettle{} }
func (m *MsgSettle) String() string { return proto.CompactTextString(m) }
func (*MsgSettle) ProtoMessage()    {}
func (*MsgSettle) Descriptor() ([]byte, []int) {
	return fileDescriptor_27434265999fa647, []int{4}
}
func (m *MsgSettle) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSettle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSettle.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSettle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSettle.Merge(m, src)
}
func (m *MsgSettle) XXX_Size() int {
	return m.Size()
}
func (m *MsgSettle) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSettle.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSettle proto.InternalMessageInfo

func (m *MsgSettle) GetOpener() string {
	if m != nil {
		return m.Opener
	}
	return ""
}

func (m *MsgSettle) GetSettlementId() []byte {
	if m != nil {
		return m.SettlementId
	}
	return nil
}

// MsgSettleResponse is the Settle response type.
type MsgSettleResponse struct {
	// Amount returned to the opener.
	Refund types.Coin `protobuf:"bytes,1,opt,name=refund,proto3" json:"refund"`
}

func (m *MsgSettleResponse) Reset()         { *m = MsgSettleResponse{} }
func (m *MsgSettleResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSettleResponse) ProtoMessage()    {}
func (*MsgSettleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_27434265999fa647, []int{5}
}
func (m *MsgSettleResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSettleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSettleResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSettleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSettleResponse.Merge(m, src)
}
func (m *MsgSettleResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSettleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSettleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSettleResponse proto.InternalMessageInfo

func (m *MsgSettleResponse) GetRefund() types.Coin {
	if m != nil {
		return m.Refund
	}
	return types.Coin{}
}

// MsgRefundSettlement closes an order by full refund.
//
// Everything not already claimed (cap − total_claimed) returns to the opener,
// outstanding claimables are zeroed, and the order becomes REFUNDED. This is
// the Emergency-Stop companion: when a task is aborted, the money comes back
// even if work was recorded mid-flight.
//
// slash_agent_id is honored only when the signer is a module authority — an
// opener's refund never slashes, so a user cannot grief an agent's bond by
// refunding orders.
type MsgRefundSettlement struct {
	// The order's opener, or a module authority.
	Opener string `protobuf:"bytes,1,opt,name=opener,proto3" json:"opener,omitempty"`
	// Order being refunded.
	SettlementId []byte `protobuf:"bytes,2,opt,name=settlement_id,json=settlementId,proto3" json:"settlement_id,omitempty"`
	// Optional: DID of an agent to slash for the failure. Ignored unless the
	// signer is a module authority.
	SlashAgentId string `protobuf:"bytes,3,opt,name=slash_agent_id,json=slashAgentId,proto3" json:"slash_agent_id,omitempty"`
}

func (m *MsgRefundSettlement) Reset()         { *m = MsgRefundSettlement{} }
func (m *MsgRefundSettlement) String() string { return proto.CompactTextString(m) }
func (*MsgRefundSettlement) ProtoMessage()    {}
func (*MsgRefundSettlement) Descriptor() ([]byte, []int) {
	return fileDescriptor_27434265999fa647, []int{6}
}
func (m *MsgRefundSettlement) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRefundSettlement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRefundSettlement.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRefundSettlement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRefundSettlement.Merge(m, src)
}
func (m *MsgRefundSettlement) XXX_Size() int {
	return m.Size()
}
func (m *MsgRefundSettlement) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRefundSettlement.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRefundSettlement proto.InternalMessageInfo

func (m *MsgRefundSettlement) GetOpener() string {
	if m != nil {
		return m.Opener
	}
	return ""
}

func (m *MsgRefundSettlement) GetSettlementId() []byte {
	if m != nil {
		return m.SettlementId
	}
	return nil
}

func (m *MsgRefundSettlement) GetSlashAgentId() string {
	if m != nil {
		return m.SlashAgentId
	}
	return ""
}

// MsgRefundSettlementResponse is the RefundSettlement response type.
type MsgRefundSettlementResponse struct {
	// Amount returned to the opener.
	Refund types.Coin `protobuf:"bytes,1,opt,name=refund,proto3" json:"refund"`
}

func (m *MsgRefundSettlementResponse) Reset()         { *m = MsgRefundSettlementResponse{} }
func (m *MsgRefundSettlementResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRefundSettlementResponse) ProtoMessage()    {}
func (*MsgRefundSettlementResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_27434265999fa647, []int{7}
}
func (m *MsgRefundSettlementResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRefundSettlementResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRefundSettlementResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRefundSettlementResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRefundSettlementResponse.Merge(m, src)
}
func (m *MsgRefundSettlementResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRefundSettlementResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRefundSettlementResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRefundSettlementResponse proto.InternalMessageInfo

func (m *MsgRefundSettlementResponse) GetRefund() types.Coin {
	if m != nil {
		return m.Refund
	}
	return types.Coin{}
}

// MsgClaim pays out an agent's accrued claimable.
//
// The whole claimable is paid and zeroed — there is no partial-claim amount
// for a caller to overstate. The marketplace commission is deducted here, at
// withdrawal, and sent to the treasury.
type MsgClaim struct {
	// Account receiving the payout. Must be the registered operator of
	// agent_id.
	Claimer string `protobuf:"bytes,1,opt,name=claimer,proto3" json:"claimer,omitempty"`
	// Order the claimable was accrued under.
	SettlementId []byte `protobuf:"bytes,2,opt,name=settlement_id,json=settlementId,proto3" json:"settlement_id,omitempty"`
	// DID of the agent whose claimable is being withdrawn.
	AgentId string `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
}

func (m *MsgClaim) Reset()         { *m = MsgClaim{} }
func (m *MsgClaim) String() string { return proto.CompactTextString(m) }
func (*MsgClaim) ProtoMessage()    {}
func (*MsgClaim) Descriptor() ([]byte, []int) {
	return fileDescriptor_27434265999fa647, []int{8}
}
func (m *MsgClaim) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgClaim) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgClaim.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgClaim) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClaim.Merge(m, src)
}
func (m *MsgClaim) XXX_Size() int {
	return m.Size()
}
func (m *MsgClaim) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClaim.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClaim proto.InternalMessageInfo

func (m *MsgClaim) GetClaimer() string {
	if m != nil {
		return m.Claimer
	}
	return ""
}

func (m *MsgClaim) GetSettlementId() []byte {
	if m != nil {
		return m.SettlementId
	}
	return nil
}

func (m *MsgClaim) GetAgentId() string {
	if m != nil {
		return m.AgentId
	}
	return ""
}

// MsgClaimResponse is the Claim response type.
type MsgClaimResponse struct {
	// Net amount paid to the claimer, after commission.
	Paid types.Coin `protobuf:"bytes,1,opt,name=paid,proto3" json:"paid"`
	// Commission diverted to the treasury.
	Commission types.Coin `protobuf:"bytes,2,opt,name=commission,proto3" json:"commission"`
}

func (m *MsgClaimResponse) Reset()         { *m = MsgClaimResponse{} }
func (m *MsgClaimResponse) String() string { return proto.CompactTextString(m) }
func (*MsgClaimResponse) ProtoMessage()    {}
func (*MsgClaimResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_27434265999fa647, []int{9}
}
func (m *MsgClaimResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgClaimResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgClaimResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgClaimResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClaimResponse.Merge(m, src)
}
func (m *MsgClaimResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgClaimResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClaimResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClaimResponse proto.InternalMessageInfo

func (m *MsgClaimResponse) GetPaid() types.Coin {
	if m != nil {
		return m.Paid
	}
	return types.Coin{}
}

func (m *MsgClaimResponse) GetCommission() types.Coin {
	if m != nil {
		return m.Commission
	}
	return types.Coin{}
}

// MsgUpdateParams sets the module parameters.
type MsgUpdateParams struct {
	// Address permitted to update params: the gov module or x/delaymsg.
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// New parameters, replacing the current set in full.
	Params Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params"`
}

func (m *MsgUpdateParams) Reset()         { *m = MsgUpdateParams{} }
func (m *MsgUpdateParams) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParams) ProtoMessage()    {}
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_27434265999fa647, []int{10}
}
func (m *MsgUpdateParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParams.Merge(m, src)
}
func (m *MsgUpdateParams) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParams.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParams proto.InternalMessageInfo

func (m *MsgUpdateParams) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateParams) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// MsgUpdateParamsResponse is the UpdateParams response type.
type MsgUpdateParamsResponse struct {
}

func (m *MsgUpdateParamsResponse) Reset()         { *m = MsgUpdateParamsResponse{} }
func (m *MsgUpdateParamsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParamsResponse) ProtoMessage()    {}
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_27434265999fa647, []int{11}
}
func (m *MsgUpdateParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParamsResponse.Merge(m, src)
}
func (m *MsgUpdateParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParamsResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgOpenSettlement)(nil), "dydxprotocol.settlement.MsgOpenSettlement")
	proto.RegisterType((*MsgOpenSettlementResponse)(nil), "dydxprotocol.settlement.MsgOpenSettlementResponse")
	proto.RegisterType((*MsgRecordSpend)(nil), "dydxprotocol.settlement.MsgRecordSpend")
	proto.RegisterType((*MsgRecordSpendResponse)(nil), "dydxprotocol.settlement.MsgRecordSpendResponse")
	proto.RegisterType((*MsgSettle)(nil), "dydxprotocol.settlement.MsgSettle")
	proto.RegisterType((*MsgSettleResponse)(nil), "dydxprotocol.settlement.MsgSettleResponse")
	proto.RegisterType((*MsgRefundSettlement)(nil), "dydxprotocol.settlement.MsgRefundSettlement")
	proto.RegisterType((*MsgRefundSettlementResponse)(nil), "dydxprotocol.settlement.MsgRefundSettlementResponse")
	proto.RegisterType((*MsgClaim)(nil), "dydxprotocol.settlement.MsgClaim")
	proto.RegisterType((*MsgClaimResponse)(nil), "dydxprotocol.settlement.MsgClaimResponse")
	proto.RegisterType((*MsgUpdateParams)(nil), "dydxprotocol.settlement.MsgUpdateParams")
	proto.RegisterType((*MsgUpdateParamsResponse)(nil), "dydxprotocol.settlement.MsgUpdateParamsResponse")
}

func init() { proto.RegisterFile("dydxprotocol/settlement/tx.proto", fileDescriptor_27434265999fa647) }

var fileDescriptor_27434265999fa647 = []byte{
	// 768 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x96, 0xcd, 0x6e, 0xd3, 0x4a,
	0x14, 0xc7, 0xe3, 0x36, 0x37, 0x6d, 0x4f, 0xd3, 0xdc, 0x5e, 0xdf, 0x8a, 0x26, 0x46, 0x72, 0x8b,
	0xa9, 0x44, 0x29, 0xd4, 0x6e, 0xd2, 0x8a, 0x4a, 0x15, 0x08, 0xb5, 0x95, 0x90, 0x2a, 0x11, 0x81,
	0x5c, 0xb5, 0x42, 0x6c, 0xc2, 0xc4, 0x1e, 0x9c, 0x41, 0xb1, 0xc7, 0xf2, 0x38, 0x51, 0xbb, 0x65,
	0xc5, 0x82, 0x05, 0x4b, 0x58, 0xf1, 0x0a, 0x2c, 0x78, 0x88, 0x2e, 0x0b, 0x2b, 0x56, 0x08, 0xb5,
	0x0b, 0x9e, 0x80, 0x3d, 0xf2, 0x78, 0xe2, 0x24, 0xfd, 0x48, 0x0c, 0x5d, 0x65, 0x3e, 0x7e, 0x67,
	0xce, 0xff, 0x7f, 0x66, 0x72, 0x64, 0x98, 0xb7, 0x0f, 0xed, 0x03, 0x3f, 0xa0, 0x21, 0xb5, 0x68,
	0xd3, 0x60, 0x38, 0x0c, 0x9b, 0xd8, 0xc5, 0x5e, 0x68, 0x84, 0x07, 0x3a, 0x5f, 0x96, 0x67, 0x7b,
	0x09, 0xbd, 0x4b, 0x28, 0x25, 0x8b, 0x32, 0x97, 0xb2, 0x1a, 0xdf, 0x33, 0xe2, 0x49, 0x1c, 0xa3,
	0xcc, 0xc6, 0x33, 0xc3, 0x65, 0x8e, 0xd1, 0x2e, 0x47, 0x3f, 0x62, 0x63, 0xc6, 0xa1, 0x0e, 0x8d,
	0x03, 0xa2, 0x91, 0x58, 0x55, 0x05, 0x5e, 0x47, 0x0c, 0x1b, 0xed, 0x72, 0x1d, 0x87, 0xa8, 0x6c,
	0x58, 0x94, 0x78, 0x62, 0x7f, 0xe1, 0x32, 0x91, 0x3e, 0x0a, 0x90, 0x2b, 0x92, 0x6a, 0x1f, 0x24,
	0xf8, 0xaf, 0xca, 0x9c, 0x27, 0x3e, 0xf6, 0x76, 0x13, 0x44, 0x5e, 0x81, 0x1c, 0xf5, 0xb1, 0x87,
	0x83, 0xa2, 0x34, 0x2f, 0x2d, 0x4e, 0x6c, 0x15, 0xbf, 0x7e, 0x5e, 0x9e, 0x11, 0x62, 0x37, 0x6d,
	0x3b, 0xc0, 0x8c, 0xed, 0x86, 0x01, 0xf1, 0x1c, 0x53, 0x70, 0x72, 0x19, 0x46, 0x2d, 0xe4, 0x17,
	0x47, 0xe6, 0xa5, 0xc5, 0xc9, 0x4a, 0x49, 0x17, 0x6c, 0xa4, 0x4d, 0x17, 0xda, 0xf4, 0x6d, 0x4a,
	0xbc, 0xad, 0xec, 0xd1, 0xf7, 0xb9, 0x8c, 0x19, 0xb1, 0xb2, 0x0c, 0x59, 0x17, 0xbb, 0xb4, 0x38,
	0x1a, 0xa5, 0x30, 0xf9, 0x78, 0x63, 0xf2, 0xf5, 0xcf, 0x4f, 0x4b, 0xe2, 0x4c, 0xed, 0x0e, 0x94,
	0xce, 0x49, 0x33, 0x31, 0xf3, 0xa9, 0xc7, 0xb0, 0x5c, 0x80, 0x11, 0x62, 0x73, 0x79, 0x79, 0x73,
	0x84, 0xd8, 0xda, 0x17, 0x09, 0x0a, 0x55, 0xe6, 0x98, 0xd8, 0xa2, 0x81, 0xbd, 0xeb, 0x63, 0xcf,
	0x96, 0xef, 0xc1, 0x84, 0x1f, 0x10, 0xcf, 0x22, 0x3e, 0x6a, 0x0e, 0x35, 0xd2, 0x45, 0xe5, 0x9b,
	0x30, 0xd5, 0x2d, 0x57, 0x8d, 0xd8, 0xdc, 0x55, 0xde, 0xcc, 0x77, 0x17, 0x77, 0x6c, 0xb9, 0x04,
	0xe3, 0xc8, 0x11, 0xfb, 0xb1, 0x83, 0x31, 0x3e, 0xdf, 0xb1, 0xe5, 0x75, 0xc8, 0x21, 0x97, 0xb6,
	0xbc, 0xb0, 0x98, 0x4d, 0x57, 0x0e, 0x81, 0x6f, 0x14, 0x22, 0xf7, 0x5d, 0x21, 0xda, 0x0b, 0xb8,
	0xd6, 0x6f, 0x29, 0x71, 0xff, 0x08, 0x0a, 0x21, 0x0d, 0x51, 0xb3, 0x16, 0xf0, 0x4d, 0x1c, 0x57,
	0x22, 0x45, 0xaa, 0x29, 0x1e, 0x66, 0x8a, 0x28, 0x8d, 0xc2, 0x44, 0x95, 0x39, 0x71, 0x79, 0xff,
	0xe2, 0xd6, 0xd3, 0x54, 0xaa, 0xff, 0x4e, 0x1f, 0xf3, 0xe7, 0x16, 0x27, 0x4c, 0xdc, 0xac, 0x43,
	0x2e, 0xc0, 0x2f, 0x5b, 0x5e, 0x6a, 0x17, 0x02, 0xd7, 0x3e, 0x4a, 0xf0, 0x3f, 0xaf, 0x50, 0x34,
	0xbb, 0xd2, 0xfb, 0x4d, 0x75, 0xe7, 0x0b, 0x50, 0x60, 0x4d, 0xc4, 0x1a, 0xb5, 0x33, 0x37, 0x9f,
	0xe7, 0xab, 0x9b, 0xce, 0x05, 0x7e, 0xf7, 0xe1, 0xfa, 0x05, 0x02, 0xaf, 0xee, 0xfc, 0xad, 0x04,
	0xe3, 0x55, 0xe6, 0x6c, 0x37, 0x11, 0x71, 0xe5, 0x0a, 0x8c, 0x59, 0xd1, 0x20, 0x85, 0xdf, 0x0e,
	0x78, 0xd5, 0x47, 0xbe, 0x91, 0x8f, 0x5c, 0x76, 0x4e, 0xd3, 0xde, 0x48, 0x30, 0xdd, 0x91, 0x93,
	0x98, 0x5b, 0x85, 0xac, 0x8f, 0x48, 0x6a, 0x6b, 0x1c, 0x96, 0x1f, 0x02, 0x58, 0xd4, 0x75, 0x09,
	0x63, 0x84, 0x7a, 0x69, 0xfb, 0x49, 0x4f, 0x88, 0xf6, 0x5e, 0x82, 0x7f, 0xab, 0xcc, 0xd9, 0xf3,
	0x6d, 0x14, 0xe2, 0xa7, 0xbc, 0xd7, 0x45, 0x9d, 0x00, 0xb5, 0xc2, 0x06, 0x0d, 0x48, 0x78, 0x38,
	0xbc, 0x13, 0x24, 0xa8, 0xfc, 0x00, 0x72, 0x71, 0xb7, 0x14, 0x42, 0xe6, 0xf4, 0x4b, 0xfa, 0xba,
	0x1e, 0x27, 0xea, 0x5c, 0x52, 0x1c, 0x24, 0xfe, 0xcf, 0xc9, 0x71, 0x5a, 0x09, 0x66, 0xcf, 0x28,
	0xeb, 0xd4, 0xaa, 0xf2, 0x2b, 0x0b, 0xa3, 0x55, 0xe6, 0xc8, 0x3e, 0x14, 0xce, 0xf4, 0xe2, 0xa5,
	0x4b, 0x73, 0x9e, 0x6b, 0x8e, 0x4a, 0x25, 0x3d, 0x9b, 0xdc, 0x92, 0x03, 0x93, 0xbd, 0x4d, 0xf3,
	0xd6, 0xa0, 0x23, 0x7a, 0x40, 0xc5, 0x48, 0x09, 0x26, 0x89, 0x9e, 0x41, 0x4e, 0x34, 0x1a, 0x6d,
	0x50, 0x68, 0xcc, 0x28, 0x4b, 0xc3, 0x99, 0xe4, 0xe4, 0x36, 0x4c, 0x9f, 0x6b, 0x01, 0x77, 0x07,
	0xcb, 0xeb, 0xa7, 0x95, 0xb5, 0x3f, 0xa1, 0x93, 0xbc, 0x7b, 0xf0, 0x4f, 0xfc, 0x07, 0xbc, 0x31,
	0x28, 0x9c, 0x23, 0xca, 0xed, 0xa1, 0x48, 0x72, 0xec, 0x2b, 0xc8, 0xf7, 0xbd, 0xde, 0xc5, 0x41,
	0xa1, 0xbd, 0xa4, 0xb2, 0x92, 0x96, 0xec, 0xe4, 0xda, 0xda, 0x3f, 0x3a, 0x51, 0xa5, 0xe3, 0x13,
	0x55, 0xfa, 0x71, 0xa2, 0x4a, 0xef, 0x4e, 0xd5, 0xcc, 0xf1, 0xa9, 0x9a, 0xf9, 0x76, 0xaa, 0x66,
	0x9e, 0xdf, 0x77, 0x48, 0xd8, 0x68, 0xd5, 0x75, 0x8b, 0xba, 0x46, 0xdf, 0xa7, 0x44, 0x7b, 0x6d,
	0xd9, 0x6a, 0x20, 0xe2, 0x19, 0xc9, 0xca, 0x41, 0xdf, 0x37, 0xd0, 0xa1, 0x8f, 0x59, 0x3d, 0xc7,
	0x37, 0x57, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0x54, 0xc6, 0xf6, 0x7d, 0x2b, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// OpenSettlement escrows an upper-bound prepayment for a delegated task.
	OpenSettlement(ctx context.Context, in *MsgOpenSettlement, opts ...grpc.CallOption) (*MsgOpenSettlementResponse, error)
	// RecordSpend records actual spend against an open order, accruing a
	// claimable for the agent that did the work.
	RecordSpend(ctx context.Context, in *MsgRecordSpend, opts ...grpc.CallOption) (*MsgRecordSpendResponse, error)
	// Settle closes an order normally, refunding what was not recorded.
	Settle(ctx context.Context, in *MsgSettle, opts ...grpc.CallOption) (*MsgSettleResponse, error)
	// RefundSettlement closes an order by full refund, zeroing outstanding
	// claimables.
	RefundSettlement(ctx context.Context, in *MsgRefundSettlement, opts ...grpc.CallOption) (*MsgRefundSettlementResponse, error)
	// Claim pays out an agent's accrued claimable, minus the marketplace
	// commission.
	Claim(ctx context.Context, in *MsgClaim, opts ...grpc.CallOption) (*MsgClaimResponse, error)
	// UpdateParams sets the module parameters.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) OpenSettlement(ctx context.Context, in *MsgOpenSettlement, opts ...grpc.CallOption) (*MsgOpenSettlementResponse, error) {
	out := new(MsgOpenSettlementResponse)
	err := c.cc.Invoke(ctx, "/dydxprotocol.settlement.Msg/OpenSettlement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RecordSpend(ctx context.Context, in *MsgRecordSpend, opts ...grpc.CallOption) (*MsgRecordSpendResponse, error) {
	out := new(MsgRecordSpendResponse)
	err := c.cc.Invoke(ctx, "/dydxprotocol.settlement.Msg/RecordSpend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) Settle(ctx context.Context, in *MsgSettle, opts ...grpc.CallOption) (*MsgSettleResponse, error) {
	out := new(MsgSettleResponse)
	err := c.cc.Invoke(ctx, "/dydxprotocol.settlement.Msg/Settle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RefundSettlement(ctx context.Context, in *MsgRefundSettlement, opts ...grpc.CallOption) (*MsgRefundSettlementResponse, error) {
	out := new(MsgRefundSettlementResponse)
	err := c.cc.Invoke(ctx, "/dydxprotocol.settlement.Msg/RefundSettlement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) Claim(ctx context.Context, in *MsgClaim, opts ...grpc.CallOption) (*MsgClaimResponse, error) {
	out := new(MsgClaimResponse)
	err := c.cc.Invoke(ctx, "/dydxprotocol.settlement.Msg/Claim", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, "/dydxprotocol.settlement.Msg/UpdateParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// OpenSettlement escrows an upper-bound prepayment for a delegated task.
	OpenSettlement(context.Context, *MsgOpenSettlement) (*MsgOpenSettlementResponse, error)
	// RecordSpend records actual spend against an open order, accruing a
	// claimable for the agent that did the work.
	RecordSpend(context.Context, *MsgRecordSpend) (*MsgRecordSpendResponse, error)
	// Settle closes an order normally, refunding what was not recorded.
	Settle(context.Context, *MsgSettle) (*MsgSettleResponse, error)
	// RefundSettlement closes an order by full refund, zeroing outstanding
	// claimables.
	RefundSettlement(context.Context, *MsgRefundSettlement) (*MsgRefundSettlementResponse, error)
	// Claim pays out an agent's accrued claimable, minus the marketplace
	// commission.
	Claim(context.Context, *MsgClaim) (*MsgClaimResponse, error)
	// UpdateParams sets the module parameters.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) OpenSettlement(ctx context.Context, req *MsgOpenSettlement) (*MsgOpenSettlementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpenSettlement not implemented")
}
func (*UnimplementedMsgServer) RecordSpend(ctx context.Context, req *MsgRecordSpend) (*MsgRecordSpendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecordSpend not implemented")
}
func (*UnimplementedMsgServer) Settle(ctx context.Context, req *MsgSettle) (*MsgSettleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Settle not implemented")
}
func (*UnimplementedMsgServer) RefundSettlement(ctx context.Context, req *MsgRefundSettlement) (*MsgRefundSettlementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefundSettlement not implemented")
}
func (*UnimplementedMsgServer) Claim(ctx context.Context, req *MsgClaim) (*MsgClaimResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Claim not implemented")
}
func (*UnimplementedMsgServer) UpdateParams(ctx context.Context, req *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_OpenSettlement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgOpenSettlement)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).OpenSettlement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dydxprotocol.settlement.Msg/OpenSettlement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).OpenSettlement(ctx, req.(*MsgOpenSettlement))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RecordSpend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRecordSpend)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RecordSpend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dydxprotocol.settlement.Msg/RecordSpend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RecordSpend(ctx, req.(*MsgRecordSpend))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_Settle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSettle)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Settle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dydxprotocol.settlement.Msg/Settle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Settle(ctx, req.(*MsgSettle))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RefundSettlement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRefundSettlement)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RefundSettlement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dydxprotocol.settlement.Msg/RefundSettlement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RefundSettlement(ctx, req.(*MsgRefundSettlement))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_Claim_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgClaim)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Claim(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dydxprotocol.settlement.Msg/Claim",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Claim(ctx, req.(*MsgClaim))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dydxprotocol.settlement.Msg/UpdateParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dydxprotocol.settlement.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OpenSettlement",
			Handler:    _Msg_OpenSettlement_Handler,
		},
		{
			MethodName: "RecordSpend",
			Handler:    _Msg_RecordSpend_Handler,
		},
		{
			MethodName: "Settle",
			Handler:    _Msg_Settle_Handler,
		},
		{
			MethodName: "RefundSettlement",
			Handler:    _Msg_RefundSettlement_Handler,
		},
		{
			MethodName: "Claim",
			Handler:    _Msg_Claim_Handler,
		},
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dydxprotocol/settlement/tx.proto",
}

func (m *MsgOpenSettlement) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgOpenSettlement) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgOpenSettlement) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Memo) > 0 {
		i -= len(m.Memo)
		copy(dAtA[i:], m.Memo)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Memo)))
		i--
		dAtA[i] = 0x1a
	}
	{
		size, err := m.Cap.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Opener) > 0 {
		i -= len(m.Opener)
		copy(dAtA[i:], m.Opener)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Opener)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgOpenSettlementResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgOpenSettlementResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgOpenSettlementResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRecordSpend) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRecordSpend) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRecordSpend) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Amount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.AgentId) > 0 {
		i -= len(m.AgentId)
		copy(dAtA[i:], m.AgentId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.AgentId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.SettlementId) > 0 {
		i -= len(m.SettlementId)
		copy(dAtA[i:], m.SettlementId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SettlementId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Principal) > 0 {
		i -= len(m.Principal)
		copy(dAtA[i:], m.Principal)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Principal)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRecordSpendResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRecordSpendResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRecordSpendResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.TotalRecorded.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *MsgSettle) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSettle) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSettle) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SettlementId) > 0 {
		i -= len(m.SettlementId)
		copy(dAtA[i:], m.SettlementId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SettlementId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Opener) > 0 {
		i -= len(m.Opener)
		copy(dAtA[i:], m.Opener)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Opener)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSettleResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSettleResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSettleResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Refund.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *MsgRefundSettlement) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRefundSettlement) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRefundSettlement) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SlashAgentId) > 0 {
		i -= len(m.SlashAgentId)
		copy(dAtA[i:], m.SlashAgentId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SlashAgentId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.SettlementId) > 0 {
		i -= len(m.SettlementId)
		copy(dAtA[i:], m.SettlementId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SettlementId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Opener) > 0 {
		i -= len(m.Opener)
		copy(dAtA[i:], m.Opener)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Opener)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRefundSettlementResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRefundSettlementResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRefundSettlementResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Refund.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *MsgClaim) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgClaim) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgClaim) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AgentId) > 0 {
		i -= len(m.AgentId)
		copy(dAtA[i:], m.AgentId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.AgentId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.SettlementId) > 0 {
		i -= len(m.SettlementId)
		copy(dAtA[i:], m.SettlementId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SettlementId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Claimer) > 0 {
		i -= len(m.Claimer)
		copy(dAtA[i:], m.Claimer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Claimer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgClaimResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgClaimResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgClaimResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Commission.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.Paid.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgOpenSettlement) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Opener)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Cap.Size()
	n += 1 + l + sovTx(uint64(l))
	l = len(m.Memo)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgOpenSettlementResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgRecordSpend) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Principal)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.SettlementId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.AgentId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgRecordSpendResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.TotalRecorded.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgSettle) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Opener)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.SettlementId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSettleResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Refund.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgRefundSettlement) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Opener)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.SettlementId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.SlashAgentId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgRefundSettlementResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Refund.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgClaim) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Claimer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.SettlementId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.AgentId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgClaimResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Paid.Size()
	n += 1 + l + sovTx(uint64(l))
	l = m.Commission.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdateParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Params.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdateParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgOpenSettlement) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgOpenSettlement: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgOpenSettlement: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Opener", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Opener = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cap", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Cap.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Memo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Memo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgOpenSettlementResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgOpenSettlementResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgOpenSettlementResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = append(m.Id[:0], dAtA[iNdEx:postIndex]...)
			if m.Id == nil {
				m.Id = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRecordSpend) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRecordSpend: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRecordSpend: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Principal", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Principal = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SettlementId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SettlementId = append(m.SettlementId[:0], dAtA[iNdEx:postIndex]...)
			if m.SettlementId == nil {
				m.SettlementId = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AgentId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AgentId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRecordSpendResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRecordSpendResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRecordSpendResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalRecorded", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalRecorded.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSettle) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSettle: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSettle: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Opener", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Opener = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SettlementId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SettlementId = append(m.SettlementId[:0], dAtA[iNdEx:postIndex]...)
			if m.SettlementId == nil {
				m.SettlementId = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSettleResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSettleResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSettleResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Refund", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Refund.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRefundSettlement) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRefundSettlement: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRefundSettlement: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Opener", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Opener = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SettlementId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SettlementId = append(m.SettlementId[:0], dAtA[iNdEx:postIndex]...)
			if m.SettlementId == nil {
				m.SettlementId = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SlashAgentId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SlashAgentId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRefundSettlementResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRefundSettlementResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRefundSettlementResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Refund", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Refund.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgClaim) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgClaim: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgClaim: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Claimer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Claimer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SettlementId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SettlementId = append(m.SettlementId[:0], dAtA[iNdEx:postIndex]...)
			if m.SettlementId == nil {
				m.SettlementId = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AgentId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AgentId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgClaimResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgClaimResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgClaimResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Paid", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Paid.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Commission", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Commission.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
